// src/routes/core.js — projects, notes, app registry, stats, DB admin.

/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   25-97   PROJECTS
 *  L   98-117  STATS / APPS
 *  L  118-160  NOTES
 *  L  161-275  DB ADMIN
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

const express = require('express');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

module.exports = function coreRoutes({ db, DB_PATH }) {
  const router = express.Router();

  // ==================== PROJECTS ====================
  router.get('/api/projects', (req, res) => {
    const { status, priority, search } = req.query;
    let query = 'SELECT * FROM projects WHERE 1=1';
    const params = [];
    if (status) { query += ' AND status = ?'; params.push(status); }
    if (priority) { query += ' AND priority = ?'; params.push(priority); }
    if (search) {
      query += ' AND (name LIKE ? OR description LIKE ? OR owner LIKE ?)';
      const s = `%${search}%`; params.push(s, s, s);
    }
    query += ' ORDER BY created_at DESC';
    db.all(query, params, (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      res.json(rows);
    });
  });

  router.get('/api/projects/:id', (req, res) => {
    db.get('SELECT * FROM projects WHERE id = ?', [req.params.id], (err, row) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!row) return res.status(404).json({ error: 'Project not found' });
      res.json(row);
    });
  });

  function validateProject(req, res, next) {
    const { name } = req.body;
    if (!name || !String(name).trim()) return res.status(400).json({ error: 'Project name is required' });
    next();
  }

  router.post('/api/projects', validateProject, (req, res) => {
    const { name, description, status, priority, progress, deadline, owner, tags } = req.body;
    const id = crypto.randomUUID();
    db.run(`INSERT INTO projects (id, name, description, status, priority, progress, deadline, owner, tags)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [id, String(name), description || '', status || 'not-started', priority || 'medium',
       progress || 0, deadline || '', owner || '', tags || ''],
      function(err) {
        if (err) return res.status(500).json({ error: err.message });
        db.get('SELECT * FROM projects WHERE id = ?', [id], (e2, row) => {
          if (e2) return res.status(500).json({ error: e2.message });
          res.json(row);
        });
      }
    );
  });

  router.put('/api/projects/:id', validateProject, (req, res) => {
    const { name, description, status, priority, progress, deadline, owner, tags } = req.body;
    db.run(`UPDATE projects SET name=?, description=?, status=?, priority=?,
            progress=?, deadline=?, owner=?, tags=? WHERE id=?`,
      [String(name), description || '', status || 'not-started', priority || 'medium',
       progress || 0, deadline || '', owner || '', tags || '', req.params.id],
      function(err) {
        if (err) return res.status(500).json({ error: err.message });
        db.get('SELECT * FROM projects WHERE id = ?', [req.params.id], (e2, row) => {
          if (e2) return res.status(500).json({ error: e2.message });
          if (!row) return res.status(404).json({ error: 'Project not found' });
          res.json(row);
        });
      }
    );
  });

  router.delete('/api/projects/:id', (req, res) => {
    db.run('DELETE FROM projects WHERE id = ?', [req.params.id], function(err) {
      if (err) return res.status(500).json({ error: err.message });
      res.json({ success: true });
    });
  });

  // ==================== STATS / APPS ====================
  router.get('/api/stats', (req, res) => {
    db.all(`SELECT COUNT(*) as total,
      SUM(CASE WHEN status='completed' THEN 1 ELSE 0 END) as completed,
      SUM(CASE WHEN status='in-progress' THEN 1 ELSE 0 END) as inProgress,
      SUM(CASE WHEN deadline < DATE('now') AND status != 'completed' THEN 1 ELSE 0 END) as overdue
    FROM projects`, [], (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      const s = rows[0];
      res.json({ total: s.total || 0, completed: s.completed || 0, inProgress: s.inProgress || 0, overdue: s.overdue || 0 });
    });
  });

  router.get('/api/apps', (req, res) => {
    db.all('SELECT * FROM app_registry WHERE enabled=1 ORDER BY sort_order, name', [], (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      res.json(rows);
    });
  });

  // ==================== NOTES ====================
  router.get('/api/notes', (req, res) => {
    db.all('SELECT * FROM notes ORDER BY updated_at DESC', [], (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      res.json(rows);
    });
  });

  function validateNote(req, res, next) {
    const { title } = req.body;
    if (!title || !String(title).trim()) return res.status(400).json({ error: 'Note title is required' });
    next();
  }

  router.post('/api/notes', validateNote, (req, res) => {
    const { title, content } = req.body;
    db.run('INSERT INTO notes (title, content) VALUES (?, ?)', [String(title), content || ''], function(err) {
      if (err) return res.status(500).json({ error: err.message });
      db.get('SELECT * FROM notes WHERE id = ?', [this.lastID], (e2, row) => {
        if (e2) return res.status(500).json({ error: e2.message });
        res.json(row);
      });
    });
  });

  router.put('/api/notes/:id', validateNote, (req, res) => {
    const { title, content } = req.body;
    db.run('UPDATE notes SET title=?, content=? WHERE id=?', [String(title), content || '', req.params.id], function(err) {
      if (err) return res.status(500).json({ error: err.message });
      db.get('SELECT * FROM notes WHERE id = ?', [req.params.id], (e2, row) => {
        if (e2) return res.status(500).json({ error: e2.message });
        res.json(row);
      });
    });
  });

  router.delete('/api/notes/:id', (req, res) => {
    db.run('DELETE FROM notes WHERE id = ?', [req.params.id], function(err) {
      if (err) return res.status(500).json({ error: err.message });
      res.json({ success: true });
    });
  });

  // ==================== DB ADMIN ====================
  const safeTable = (name) => String(name || '').replace(/[^a-zA-Z0-9_]/g, '');

  router.get('/api/db/tables', (req, res) => {
    db.all("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'", [], (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      res.json(rows.map(r => r.name));
    });
  });

  router.get('/api/db/tables/:name', (req, res) => {
    const tableName = safeTable(req.params.name);
    if (!tableName) return res.status(400).json({ error: 'Invalid table name' });

    db.all(`PRAGMA table_info(${tableName})`, [], (err, columns) => {
      if (err) return res.status(500).json({ error: err.message });

      const page = parseInt(req.query.page) || 1;
      const limit = Math.min(parseInt(req.query.limit) || 50, 200);
      const offset = (page - 1) * limit;
      const search = req.query.search;

      let query = `SELECT * FROM ${tableName}`;
      const params = [];
      if (search && columns.length > 0) {
        const searchCols = columns.map(c => `"${c.name}"`).join(', ');
        query += ` WHERE (${searchCols} LIKE ?)`;
        params.push(`%${search}%`);
      }
      query += ' LIMIT ? OFFSET ?';
      params.push(limit, offset);

      db.all(query, params, (err2, rows) => {
        if (err2) return res.status(500).json({ error: err2.message });
        db.get(`SELECT COUNT(*) as count FROM ${tableName}`, [], (err3, countRow) => {
          if (err3) return res.status(500).json({ error: err3.message });
          res.json({ columns, rows, pagination: { page, limit, total: countRow.count, pages: Math.ceil(countRow.count / limit) } });
        });
      });
    });
  });

  router.post('/api/db/tables/:name/rows', (req, res) => {
    const tableName = safeTable(req.params.name);
    if (!tableName) return res.status(400).json({ error: 'Invalid table name' });

    db.all(`PRAGMA table_info(${tableName})`, [], (err, columns) => {
      if (err) return res.status(500).json({ error: err.message });
      const colNames = columns.filter(c => c.name !== 'id').map(c => c.name);
      const values = colNames.map(col => req.body[col] ?? null);
      const placeholders = colNames.map(() => '?').join(', ');
      db.run(`INSERT INTO ${tableName} (${colNames.join(', ')}) VALUES (${placeholders})`, values, function(err2) {
        if (err2) return res.status(500).json({ error: err2.message });
        res.json({ id: this.lastID, success: true });
      });
    });
  });

  router.put('/api/db/tables/:name/rows/:id', (req, res) => {
    const tableName = safeTable(req.params.name);
    if (!tableName) return res.status(400).json({ error: 'Invalid table name' });

    db.all(`PRAGMA table_info(${tableName})`, [], (err, columns) => {
      if (err) return res.status(500).json({ error: err.message });
      const colNames = columns.filter(c => c.name !== 'id').map(c => c.name);
      const sets = colNames.map(col => `"${col}" = ?`).join(', ');
      const values = [...colNames.map(col => req.body[col] ?? null), req.params.id];
      db.run(`UPDATE ${tableName} SET ${sets} WHERE id = ?`, values, function(err2) {
        if (err2) return res.status(500).json({ error: err2.message });
        res.json({ success: true });
      });
    });
  });

  router.delete('/api/db/tables/:name/rows/:id', (req, res) => {
    const tableName = safeTable(req.params.name);
    if (!tableName) return res.status(400).json({ error: 'Invalid table name' });
    db.run(`DELETE FROM ${tableName} WHERE id = ?`, [req.params.id], function(err) {
      if (err) return res.status(500).json({ error: err.message });
      res.json({ success: true });
    });
  });

  router.post('/api/db/query', (req, res) => {
    const { sql } = req.body;
    if (!sql || !String(sql).trim()) return res.status(400).json({ error: 'SQL query required' });
    const trimmed = String(sql).trim().toUpperCase();
    if (!/^(SELECT|INSERT|UPDATE|DELETE|PRAGMA|VACUUM)/.test(trimmed)) {
      return res.status(400).json({ error: 'Only SELECT, INSERT, UPDATE, DELETE, PRAGMA, VACUUM allowed' });
    }
    if (trimmed.startsWith('SELECT') || trimmed.startsWith('PRAGMA')) {
      db.all(sql, [], (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ rows, success: true });
      });
    } else {
      db.run(sql, [], function(err) {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ changes: this.changes, lastID: this.lastID, success: true });
      });
    }
  });

  router.get('/api/db/backup', (req, res) => {
    const backupPath = DB_PATH.replace(/\.db$/, `_backup_${Date.now()}.db`);
    fs.copyFile(DB_PATH, backupPath, (err) => {
      if (err) return res.status(500).json({ error: err.message });
      // 60s window for the download to start before we clean up.
      setTimeout(() => fs.unlink(backupPath, () => {}), 60000);
      res.download(backupPath, 'bobs-apps-backup.db');
    });
  });

  return router;
};
