// src/routes/rag.js — RAG API (index / status / query / reindex / delete).
// All Python work goes through rag/cli.py with argv — no inline `python3 -c` strings,
// no shell-escaping bugs. Timeouts are generous: the local model spends ~50s on
// reasoning before first token, so a 60s ceiling was just barely failing.

/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   72-82   POST   /api/rag/index
 *  L   83-103  GET    /api/rag/status
 *  L  104-149  GET    /api/rag/models
 *  L  150-163  GET    /api/rag/sessions
 *  L  164-171  POST   /api/rag/sessions
 *  L  172-179  GET    /api/rag/sessions/:id/messages
 *  L  180-189  DELETE /api/rag/sessions/:id
 *  L  190-255  POST   /api/rag/query
 *  L  256-276  POST   /api/rag/models/warm
 *  L  277-297  POST   /api/rag/reindex/:id
 *  L  298-313  DELETE /api/rag/delete/:id
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

const express = require('express');
const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');

module.exports = function ragRoutes({ db, DOCS_DIR, DB_PATH }) {
  const router = express.Router();
  const CLI = path.join(__dirname, '..', '..', 'rag', 'cli.py');
  // Resolve the project venv's interpreter directly — no PATH games.
  const VENV_PY = path.join(__dirname, '..', '..', '.venv', 'bin', 'python3');
  const PY = process.env.PYTHON || (fs.existsSync(VENV_PY) ? VENV_PY : 'python3');
  // Query budget covers: model load (first call) + retrieval + generation.
  const QUERY_TIMEOUT_MS = parseInt(process.env.RAG_QUERY_TIMEOUT_MS || '300000', 10);
  const LM_CHAT_URL = process.env.LM_STUDIO_URL || 'http://192.168.0.191:1234/v1/chat/completions';
  // Same env the python side reads; derive the models endpoint from the chat URL.
  const LM_MODELS_URL = LM_CHAT_URL.replace(/\/chat\/completions\/?$/, '/models');

  // Warm requests only need to trigger the load; LM Studio holds the request while it
  // loads from disk. Anything past this is answered {pending:true} and the UI polls state.
  const WARM_TIMEOUT_MS = parseInt(process.env.RAG_WARM_TIMEOUT_MS || '20000', 10);

  function runCli(args, timeoutMs, done) {
    execFile(PY, [CLI, ...args], {
      encoding: 'utf8', maxBuffer: 50 * 1024 * 1024, timeout: timeoutMs
    }, (err, output, stderr) => {
      const tail = String(stderr || '').trim().split('\n').slice(-8).join('\n');
      if (err) {
        err.cliStderr = tail;  // python tracebacks go to stderr — without this the route is blind
        return done(err);
      }
      let parsed;
      try {
        parsed = JSON.parse(output.trim());
      } catch (e) {
        // The CLI prints exactly one JSON object on stdout; anything else is a bug.
        const e2 = new Error('Malformed RAG CLI output');
        e2.raw_output = output.trim().slice(0, 4000);
        e2.cliStderr = tail;
        return done(e2);
      }
      done(null, parsed);
    });
  }

  // ---- index all unindexed docs --------------------------------------------
  router.post('/api/rag/index', (req, res) => {
    runCli(['index-all', DB_PATH], 300000, (err, result) => {
      if (err) {
        const details = [err.details, err.cliStderr, err.raw_output].filter(Boolean).join(' | ') || err.message;
        return res.status(500).json({ error: 'Indexing failed', details });
      }
      res.json({ success: true, ...result });
    });
  });

  // ---- status ---------------------------------------------------------------
  router.get('/api/rag/status', (req, res) => {
    db.all(`SELECT COUNT(*) as total_docs,
                   SUM(CASE WHEN indexed = 1 THEN 1 ELSE 0 END) as indexed_count,
                   COALESCE(SUM(chunk_count), 0) as total_chunks
            FROM documents`, [], (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      const s = rows[0];
      res.json({
        total_docs: s.total_docs || 0,
        indexed_count: s.indexed_count || 0,
        chunk_count: s.total_chunks || 0
      });
    });
  });

  // ---- list LM Studio models for the model picker ---------------------------
  // Proxy (not direct browser->LM Studio): the SPA is same-origin served, and .191
  // has no CORS. Embedding models can't generate answers, so they're filtered out.
  // Loaded state comes from LM Studio's native /api/v0/models (v1 has no `state`).
  // Picking a NOT-loaded model costs a cold load (minutes for big GGUFs) because
  // LM Studio keeps one instance resident — surfacing that here beats guessing.
  router.get('/api/rag/models', async (req, res) => {
    try {
      const base = LM_MODELS_URL.replace(/\/models\/?$/, '');
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 4000);  // LM Studio down shouldn't hang the SPA
      let models = [];
      try {
        // Native API first: it knows state (loaded / loading / not-loaded).
        const nv = await fetch(base.replace(/\/v1$/, '') + '/api/v0/models', { signal: ctrl.signal });
        if (nv.ok) {
          const jd = await nv.json();
          models = (jd.data || [])
            .filter(m => m.id && !/embed|rerank/i.test(m.id))
            .map(m => ({ id: m.id, state: m.state || 'unknown' }))
            .sort((a, b) => a.id.localeCompare(b.id));
        }
      } catch { /* fall through to OpenAI-style list */ }
      if (!models.length) {
        const r = await fetch(LM_MODELS_URL, { signal: ctrl.signal });
        if (!r.ok) return res.status(502).json({ error: `LM Studio returned ${r.status}` });
        const data = await r.json();
        models = (data.data || [])
          .map(m => ({ id: m.id, state: 'unknown' }))
          .filter(m => m.id && !/embed|rerank/i.test(m.id))
          .sort((a, b) => a.id.localeCompare(b.id));
      } else {
        models = models.filter(m => m.state !== 'error');
      }
      res.json({ models });
    } catch (e) {
      res.status(502).json({ error: `LM Studio unreachable: ${e.message}` });
    }
  });

  // ---- chat sessions ------------------------------------------------------------
  // ChatGPT-style threads: GET lists sessions, GET /sessions/:id fetches one thread,
  // POST creates one (lazily titled from its first question), DELETE removes a thread.
  // Messages are still written by POST /query below — history bookkeeping never happens
  // through a separate user-facing write path, so pairs stay atomic per exchange.

  const rowToMessage = (r) => ({
    id: r.id, role: r.role, content: r.content, model: r.model || null,
    llm_offline: !!r.llm_offline, created_at: r.created_at,
    sources: (() => { try { return JSON.parse(r.sources_json) || []; } catch { return []; } })(),
  });

  router.get('/api/rag/sessions', (req, res) => {
    // Empty sessions are hidden from the list — a "New chat" click that's never used
    // shouldn't litter the sidebar. They exist server-side until first message.
    db.all(
      `SELECT s.id, s.title, s.created_at, s.updated_at, COUNT(m.id) AS n
       FROM rag_sessions s LEFT JOIN rag_messages m ON m.session_id = s.id
       GROUP BY s.id HAVING n > 0 ORDER BY s.updated_at DESC LIMIT 200`, [],
      (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ sessions: rows.map(r => ({ id: r.id, title: r.title || 'Untitled', created_at: r.created_at, updated_at: r.updated_at, messages: r.n })) });
      }
    );
  });

  router.post('/api/rag/sessions', (req, res) => {
    const id = require('crypto').randomUUID();
    db.run(`INSERT INTO rag_sessions (id, title, updated_at) VALUES (?, '', CURRENT_TIMESTAMP)`, [id], (err) => {
      if (err) return res.status(500).json({ error: err.message });
      res.json({ id });
    });
  });

  router.get('/api/rag/sessions/:id/messages', (req, res) => {
    db.all(`SELECT id, role, content, model, llm_offline, sources_json, created_at
            FROM rag_messages WHERE session_id = ? ORDER BY id ASC`, [req.params.id], (err, rows) => {
      if (err) return res.status(500).json({ error: err.message });
      res.json({ messages: rows.map(rowToMessage) });
    });
  });

  router.delete('/api/rag/sessions/:id', (req, res) => {
    db.run(`DELETE FROM rag_sessions WHERE id = ?`, [req.params.id], (err) => {
      if (err) return res.status(500).json({ error: err.message });
      // FK has no ON DELETE CASCADE (SQLite default), so delete messages explicitly.
      db.run(`DELETE FROM rag_messages WHERE session_id = ?`, [req.params.id], () =>
        res.json({ success: true }));
    });
  });

  // ---- query (retrieve + generate) ------------------------------------------
  router.post('/api/rag/query', (req, res) => {
    const { query, model } = req.body;
    if (!query || !String(query).trim()) return res.status(400).json({ error: 'Query text is required' });

    // Empty/absent model keeps the old behavior (LM Studio's loaded model).
    const args = ['query', String(query)];
    if (model && String(model).trim()) args.push('--model', String(model).trim());

    // Settings menu knobs. Everything here becomes argv to the python CLI, so each
    // value is range-checked/enum-checked first — never pass user strings through raw.
    const o = req.body.options || {};
    const intArg = (v, lo, hi) => { const n = Number(v); return Number.isInteger(n) && n >= lo && n <= hi ? n : null; };
    const k = intArg(o.k, 1, 20);
    if (k) args.push('--k', String(k));
    const mt = intArg(o.max_tokens, 256, 65536);
    if (mt) args.push('--max-tokens', String(mt));
    const temp = Number(o.temperature);
    if (Number.isFinite(temp) && temp >= 0 && temp <= 2) args.push('--temperature', String(temp));
    if (['low', 'medium', 'high'].includes(o.reasoning_effort)) args.push('--reasoning-effort', o.reasoning_effort);

    // One telemetry line per request. The CLI's stdout is discarded unless it fails, so
    // without this the container log has zero record of any query (cold-start bugs were
    // undiagnosable for exactly this reason).
    const t0 = Date.now();
    runCli(args, QUERY_TIMEOUT_MS, (err, result) => {
      const ms = Date.now() - t0;
      if (err) {
        console.error(`[rag] query FAILED model=${model || '(loaded)'} ms=${ms} err=${err.message} stderr=${(err.cliStderr || '').slice(0, 400)}`);
        // raw_output/cliStderr are attached by runCli — without them a prod 500 is unreadable.
        const details = [err.message, err.cliStderr, err.raw_output].filter(Boolean).join(' | ');
        return res.status(500).json({ error: 'Query failed', details });
      }
      console.log(`[rag] query model=${model || '(loaded)'} offline=${result && result.llm_offline ? 'yes' : 'no'} ms=${ms}`);
      // Persist the successful exchange into its session thread. Insertion failure
      // must not fail the request — answer delivery outranks history bookkeeping.
      const sessionId = String(req.body.session_id || '').slice(0, 64) || 'legacy';
      const sourcesJson = JSON.stringify(result.sources || []);
      db.serialize(() => {
        // The frontend always sends a real session id; 'legacy' is the fallback for old/odd
        // clients. Ensure its row exists so a fallback insert can't become an invisible thread.
        if (sessionId === 'legacy') {
          db.run(`INSERT OR IGNORE INTO rag_sessions (id, title) VALUES ('legacy', 'Older history')`);
        }
        db.run(
          `INSERT INTO rag_messages (session_id, role, content, model, llm_offline, sources_json) VALUES
           (?, 'user', ?, NULL, 0, '[]'),
           (?, 'assistant', ?, ?, ?, ?)`,
          [sessionId, String(query), sourcesJson, sessionId, result.answer || '', String(model || ''), result.llm_offline ? 1 : 0, sourcesJson],
          (err2) => { if (err2) console.error('[rag] history insert failed:', err2.message); }
        );
        // Lazily title the session from its first question, and bump updated_at so
        // the sidebar sorts by last activity. Titles stay: user rename can come later.
        db.run(
          `UPDATE rag_sessions SET updated_at = CURRENT_TIMESTAMP,
             title = CASE WHEN title = '' THEN ? ELSE title END
           WHERE id = ?`, [String(query).slice(0, 80), sessionId], () => {}
        );
      });
      res.json(result);
    });
  });

  // ---- warm a picked model into memory (fire-and-forget from the UI) --------
  // Picking an unloaded 35B used to make your first question pay the multi-minute disk
  // load, inside our query timeout — so it died as a failed question. This starts the
  // load with a 1-token completion instead; LM Studio has no lifecycle API (probed).
  router.post('/api/rag/models/warm', async (req, res) => {
    const model = String(req.body.model || '').trim();
    if (!model) return res.status(400).json({ error: 'model required' });
    try {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), WARM_TIMEOUT_MS);
      const r = await fetch(LM_CHAT_URL, {
        method: 'POST', signal: ctrl.signal,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ model, messages: [{ role: 'user', content: 'warm up' }], max_tokens: 1 }),
      }).finally(() => clearTimeout(t));
      console.log(`[rag] warm model=${model} lm_status=${r.status}`);
      res.json({ ok: r.ok });
    } catch (e) {
      // Timeout here usually means "still loading" — not an error the UI needs to hear about.
      console.log(`[rag] warm model=${model} note=${e.message}`);
      res.json({ ok: true, pending: true });
    }
  });

  // ---- reindex one doc ------------------------------------------------------
  router.post('/api/rag/reindex/:id', (req, res) => {
    const docId = req.params.id;
    db.get('SELECT id, title, filename, file_type FROM documents WHERE id = ?', [docId], (err, row) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!row) return res.status(404).json({ error: 'Document not found' });

      const filePath = path.join(DOCS_DIR, String(row.filename).replace(/[^a-zA-Z0-9._-]/g, ''));
      runCli(['reindex-one', docId, filePath, row.title, row.filename, row.file_type], 120000, (err2, result) => {
        if (err2) return res.status(500).json({ error: 'Reindexing failed', details: err2.message });

        if (result.success) {
          db.run('UPDATE documents SET indexed=1, chunk_count=? WHERE id=?', [result.chunk_count || 0, docId]);
        } else {
          db.run('UPDATE documents SET indexed=0, chunk_count=0 WHERE id=?', [docId]);
        }
        res.json(result);
      });
    });
  });

  // ---- delete chunks --------------------------------------------------------
  router.delete('/api/rag/delete/:id', (req, res) => {
    const docId = req.params.id;
    db.get('SELECT id FROM documents WHERE id = ?', [docId], (err, row) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!row) return res.status(404).json({ error: 'Document not found' });

      runCli(['delete-chunks', docId], 30000, (err2) => {
        if (err2) return res.status(500).json({ error: 'Failed to delete chunks', details: err2.message });
        db.run('UPDATE documents SET indexed=0, chunk_count=0 WHERE id=?', [docId]);
        res.json({ success: true });
      });
    });
  });

  return router;
};
