// src/routes/slideshows.js — Photo Slideshow API (see docs/archive/SLIDESHOW_PLAN.md).
// Shows + ordered photos live in SQLite; image files on disk named <uuid>.<ext>
// so two uploads can never collide or path-escape. Uploads are raw bytes
// (docs.js pattern): Content-Type decides the extension, a Transform stream
// enforces the size cap mid-flight instead of after the disk already ate it.
// Audio: music_url is a YouTube link the SERVER renders to local files via
// yt-dlp (src/audio.js) — embeds are dead on bare-IP origins (Error 153).

/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   62-73   GET    /api/slideshows
 *  L   74-93   POST   /api/slideshows
 *  L   94-121  GET    /api/slideshows/:id
 *  L  122-175  PATCH  /api/slideshows/:id
 *  L  176-207  DELETE /api/slideshows/:id
 *  L  208-274  POST   /api/slideshows/:id/photos
 *  L  275-296  PATCH  /api/slideshows/photos/:pid
 *  L  297-311  DELETE /api/slideshows/photos/:pid
 *  L  312-348  PUT    /api/slideshows/:id/order
 *  L  349-362  GET    /api/slideshow-audio/:filename
 *  L  363-375  GET    /api/slideshow-photos/:filename
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

const express = require('express');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const { Transform } = require('stream');
const { AUDIO_EXT } = require('../audio');

// Content-Type → extension whitelist. HEIC/HEVC iPhone originals are handled
// client-side (canvas re-encode to JPEG before upload); server stays pixel-blind.
const MIME_EXT = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
  'image/gif': 'gif',
};
const EXT_MIME = Object.fromEntries(Object.entries(MIME_EXT).map(([m, e]) => [e, m]));

module.exports = function slideshowRoutes({ db, SLIDESHOW_DIR, audioJobs }) {
  const router = express.Router();

  const MAX_PHOTO_BYTES = 50 * 1024 * 1024;   // per photo (plan NFR)
  const MAX_SHOW_BYTES = 1024 * 1024 * 1024;  // per show total (plan NFR)

  const clampDuration = (v) => {
    if (v === null || v === undefined || v === '') return null;
    const n = Number(v);
    if (!Number.isFinite(n) || n < 1 || n > 600) return undefined; // sentinel: invalid
    return n;
  };

  // ---- shows: list / create --------------------------------------------------

  router.get('/api/slideshows', (req, res) => {
    db.all(
      `SELECT s.*, COUNT(p.id) AS photo_count
       FROM slideshows s LEFT JOIN slideshow_photos p ON p.slideshow_id = s.id
       GROUP BY s.id ORDER BY s.created_at DESC`,
      [], (err, rows) => {
        if (err) return res.status(500).json({ error: err.message });
        res.json({ slideshows: rows });
      }
    );
  });

  router.post('/api/slideshows', (req, res) => {
    const { title } = req.body || {};
    if (!title || !String(title).trim()) return res.status(400).json({ error: 'Title is required' });

    const id = crypto.randomUUID();
    db.run(
      `INSERT INTO slideshows (id, title) VALUES (?, ?)`,
      [id, String(title).trim()],
      function (err) {
        if (err) return res.status(500).json({ error: err.message });
        db.get('SELECT * FROM slideshows WHERE id = ?', [id], (e2, row) => {
          if (e2) return res.status(500).json({ error: e2.message });
          res.json({ ...row, photo_count: 0 });
        });
      }
    );
  });

  // ---- show detail -------------------------------------------------------------
  // Full editor/player payload in one round-trip: show meta + photos ordered.
  router.get('/api/slideshows/:id', (req, res) => {
    db.get('SELECT * FROM slideshows WHERE id = ?', [req.params.id], (err, row) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!row) return res.status(404).json({ error: 'Slideshow not found' });
      db.all(
        `SELECT id, slideshow_id, filename, caption, position, duration_override, created_at
         FROM slideshow_photos WHERE slideshow_id = ? ORDER BY position ASC`,
        [req.params.id], (e2, photos) => {
          if (e2) return res.status(500).json({ error: e2.message });
          db.all(
            `SELECT id, filename, title, duration, position FROM slideshow_tracks
             WHERE slideshow_id = ? ORDER BY position ASC`,
            [req.params.id], (e3, tracks) => {
              if (e3) return res.status(500).json({ error: e3.message });
              res.json({ ...row, photos, tracks: tracks || [] });
            }
          );
        }
      );
    });
  });

  // ---- show update ---------------------------------------------------------------
  // PATCH with any subset. music_url accepts a raw YouTube link; we store it as-is
  // (driver parses IDs client-side) but sanity-check the host so typos fail loudly
  // at edit time, not silently on show night.
  const YOUTUBE_HOSTS = /^(https?:\/\/)?((www|music|m)\.)?(youtube\.com|youtu\.be|youtube-nocookie\.com)\/\S*$/i;

  router.patch('/api/slideshows/:id', (req, res) => {
    const b = req.body || {};
    const sets = [], params = [];
    let pendingAudio = null;

    if (b.title !== undefined) {
      const t = String(b.title).trim();
      if (!t) return res.status(400).json({ error: 'Title cannot be empty' });
      sets.push('title = ?'); params.push(t);
    }
    if (b.music_url !== undefined) {
      const u = String(b.music_url).trim();
      if (u && !YOUTUBE_HOSTS.test(u)) {
        return res.status(400).json({ error: 'music_url must be a youtube.com or youtu.be URL (or empty for silent shows)' });
      }
      sets.push('music_url = ?'); params.push(u);
      // Fire the local-audio render AFTER the UPDATE lands (below), but decide
      // now whether it's needed so we don't re-download on every unrelated PATCH.
      pendingAudio = { url: u };  // handled after UPDATE succeeds
    }
    if (b.mode !== undefined) {
      if (!['timed', 'track'].includes(b.mode)) return res.status(400).json({ error: "mode must be 'timed' or 'track'" });
      sets.push('mode = ?'); params.push(b.mode);
    }
    if (b.per_slide_seconds !== undefined) {
      const n = Number(b.per_slide_seconds);
      if (!Number.isInteger(n) || n < 1 || n > 600) return res.status(400).json({ error: 'per_slide_seconds must be an integer 1-600' });
      sets.push('per_slide_seconds = ?'); params.push(n);
    }
    if (b.transition !== undefined) {
      if (!['crossfade', 'cut', 'kenburns'].includes(b.transition)) return res.status(400).json({ error: "transition must be crossfade|cut|kenburns" });
      sets.push('transition = ?'); params.push(b.transition);
    }
    if (b.loop !== undefined) {
      sets.push('loop = ?'); params.push(b.loop ? 1 : 0);
    }
    if (!sets.length) return res.status(400).json({ error: 'No updatable fields in body' });

    db.run(`UPDATE slideshows SET ${sets.join(', ')} WHERE id = ?`, [...params, req.params.id],
      function (err) {
        if (err) return res.status(500).json({ error: err.message });
        if (!this.changes) return res.status(404).json({ error: 'Slideshow not found' });
        // Music actually changed → render it locally (fire-and-forget; the UI
        // polls audio_status via GET /:id and shows progress there).
        if (pendingAudio && audioJobs) {
          if (pendingAudio.url) audioJobs.start(req.params.id, pendingAudio.url);
          else audioJobs.clear(req.params.id);
        }
        db.get('SELECT * FROM slideshows WHERE id = ?', [req.params.id], (e2, row) => res.json(row));
      }
    );
  });

  // ---- show delete (cascade photos + files on disk) -------------------------------
  router.delete('/api/slideshows/:id', (req, res) => {
    db.get('SELECT id FROM slideshows WHERE id = ?', [req.params.id], async (err, row) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!row) return res.status(404).json({ error: 'Slideshow not found' });

      if (audioJobs) { audioJobs.clear(req.params.id); } // stop nothing? at least wipe files+rows

      const photos = await new Promise((resolve, reject) =>
        db.all('SELECT filename FROM slideshow_photos WHERE slideshow_id = ?', [req.params.id],
          (e, r) => e ? reject(e) : resolve(r)));

      // Row deletion first: an unlink failure then leaves log-spam and orphan
      // files, never a DB row pointing at nothing. Photos are deleted explicitly —
      // foreign_keys pragma is OFF in this connection, so ON DELETE CASCADE is
      // documentation, not enforcement.
      db.run('DELETE FROM slideshow_photos WHERE slideshow_id = ?', [req.params.id], (e1) => {
        if (e1) return res.status(500).json({ error: e1.message });
        db.run('DELETE FROM slideshows WHERE id = ?', [req.params.id], (e2) => {
        if (e2) return res.status(500).json({ error: e2.message });
        const orphans = [];
        for (const p of photos) {
          try { fs.unlinkSync(path.join(SLIDESHOW_DIR, path.basename(p.filename))); }
          catch (ue) { if (ue.code !== 'ENOENT') orphans.push(p.filename); }
        }
        res.json({ deleted: true, orphaned_files: orphans });
        });
      });
    });
  });

  // ---- photo upload ---------------------------------------------------------------
  // POST /api/slideshows/:id/photos?caption=... body = raw image bytes.
  router.post('/api/slideshows/:id/photos', (req, res) => {
    const showId = req.params.id;
    db.get('SELECT id FROM slideshows WHERE id = ?', [showId], async (err, show) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!show) return res.status(404).json({ error: 'Slideshow not found' });

      const ext = MIME_EXT[req.headers['content-type']];
      if (!ext) {
        return res.status(400).json({ error: `Unsupported Content-Type; send one of: ${Object.keys(MIME_EXT).join(', ')}` });
      }

      // Enforce the per-show budget before accepting a single byte, then stream.
      db.get('SELECT COALESCE(SUM(file_size),0) AS used FROM slideshow_photos WHERE slideshow_id = ?', [showId],
        (e2, { used }) => {
            if (e2) return res.status(500).json({ error: e2.message });
            if (used >= MAX_SHOW_BYTES) {
              return res.status(413).json({ error: 'Show has reached its 1 GB photo budget' });
            }

            let received = 0, capped = false;
            const limiter = new Transform({
              transform(chunk, _enc, cb) {
                received += chunk.length;
                if (received > MAX_PHOTO_BYTES && !capped) { capped = true; return cb(new Error('photo too large')); }
                cb(null, chunk);
              },
            });

            const id = crypto.randomUUID();
            const filename = `${id}.${ext}`;
            const dest = path.join(SLIDESHOW_DIR, filename);
            fs.mkdirSync(SLIDESHOW_DIR, { recursive: true });

            const out = fs.createWriteStream(dest);
            limiter.on('error', (e) => {
              out.destroy();
              fs.unlink(dest, () => {});
              res.status(413).json({ error: `Photo exceeds ${MAX_PHOTO_BYTES / 1024 / 1024} MB cap` });
            });
            out.on('error', (e) => { fs.unlink(dest, () => {}); if (!res.headersSent) res.status(500).json({ error: e.message }); });
            out.on('finish', () => {
              // position = end of order; ties broken by insertion time is fine for fresh uploads
              db.serialize(() => {
                db.get('SELECT COALESCE(MAX(position),-1)+1 AS next FROM slideshow_photos WHERE slideshow_id = ?', [showId],
                  (e3, { next }) => {
                    if (e3) return res.status(500).json({ error: e3.message });
                    const caption = String(req.query.caption || '').slice(0, 280);
                    db.run(
                      `INSERT INTO slideshow_photos (id, slideshow_id, filename, caption, position, file_size)
                       VALUES (?, ?, ?, ?, ?, ?)`,
                      [id, showId, filename, caption, next, received],
                      (e4) => {
                        if (e4) return res.status(500).json({ error: e4.message });
                        db.get('SELECT id, slideshow_id, filename, caption, position, duration_override, file_size FROM slideshow_photos WHERE id = ?', [id],
                          (e5, row) => res.json(row));
                      }
                    );
                  });
              });
            });
            req.pipe(limiter).pipe(out);
        });
    });
  });

  // ---- photo update / delete --------------------------------------------------------

  router.patch('/api/slideshows/photos/:pid', (req, res) => {
    const b = req.body || {};
    const sets = [], params = [];
    if (b.caption !== undefined) { sets.push('caption = ?'); params.push(String(b.caption).slice(0, 280)); }
    if (b.duration_override !== undefined) {
      const d = clampDuration(b.duration_override);
      if (d === undefined && b.duration_override !== null && b.duration_override !== '') {
        return res.status(400).json({ error: 'duration_override must be 1-600 seconds or null' });
      }
      sets.push('duration_override = ?'); params.push(d);
    }
    if (!sets.length) return res.status(400).json({ error: 'No updatable fields in body' });

    db.run(`UPDATE slideshow_photos SET ${sets.join(', ')} WHERE id = ?`, [...params, req.params.pid],
      function (err) {
        if (err) return res.status(500).json({ error: err.message });
        if (!this.changes) return res.status(404).json({ error: 'Photo not found' });
        db.get('SELECT * FROM slideshow_photos WHERE id = ?', [req.params.pid], (e2, row) => res.json(row));
      }
    );
  });

  router.delete('/api/slideshows/photos/:pid', (req, res) => {
    db.get('SELECT filename FROM slideshow_photos WHERE id = ?', [req.params.pid], (err, row) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!row) return res.status(404).json({ error: 'Photo not found' });
      db.run('DELETE FROM slideshow_photos WHERE id = ?', [req.params.pid], (e2) => {
        if (e2) return res.status(500).json({ error: e2.message });
        fs.unlink(path.join(SLIDESHOW_DIR, path.basename(row.filename)), () => {});
        res.json({ deleted: true });
      });
    });
  });

  // ---- reorder ------------------------------------------------------------------------
  // PUT {photo_ids: [...]} — the full new order. Transaction so a mid-list
  // failure can't leave two photos at position 3.
  router.put('/api/slideshows/:id/order', (req, res) => {
    const ids = req.body && req.body.photo_ids;
    if (!Array.isArray(ids) || !ids.length) return res.status(400).json({ error: 'photo_ids must be a non-empty array' });

    db.get('SELECT id FROM slideshows WHERE id = ?', [req.params.id], (err, show) => {
      if (err) return res.status(500).json({ error: err.message });
      if (!show) return res.status(404).json({ error: 'Slideshow not found' });

      db.all('SELECT id FROM slideshow_photos WHERE slideshow_id = ?', [req.params.id], (e2, rows) => {
        if (e2) return res.status(500).json({ error: e2.message });
        const existing = new Set(rows.map(r => r.id));
        const incoming = new Set(ids);
        // Reject duplicates up front; a SQL param-per-id beats a regex placeholder list.
        if (incoming.size !== ids.length) return res.status(400).json({ error: 'photo_ids contains duplicates' });
        if (incoming.size !== existing.size || ![...existing].every(id => incoming.has(id))) {
          return res.status(400).json({ error: 'photo_ids must list every photo of this slideshow exactly once' });
        }

        db.serialize(() => {
          db.run('BEGIN');
          let failed = null;
          ids.forEach((pid, pos) => {
            db.run('UPDATE slideshow_photos SET position = ? WHERE id = ? AND slideshow_id = ?', [pos, pid, req.params.id],
              (e3) => { if (e3 && !failed) failed = e3; });
          });
          db.run(failed ? 'ROLLBACK' : 'COMMIT');
          if (failed) return res.status(500).json({ error: failed.message });
          res.json({ ordered: ids.length });
        });
      });
    });
  });

  // ---- track bytes (downloaded background music) -----------------------------------------
  // Same immutability logic as photos: UUID-ish template names, served inline.
  // Range support matters here — <audio> on Safari issues Range requests and a
  // server that ignores them gets scrubbing to jump only after full buffering.
  router.get('/api/slideshow-audio/:filename', (req, res) => {
    const fn = path.basename(req.params.filename);
    const ext = fn.split('.').pop().toLowerCase();
    if (!AUDIO_EXT[ext]) return res.status(400).json({ error: 'Bad filename' });
    const filePath = path.join(audioJobs.audioDir, fn);
    if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'Track not found' });
    res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
    // res.sendFile handles Range/206 + Content-Length for us (Express native).
    res.sendFile(filePath);
  });

  // ---- photo bytes ----------------------------------------------------------------------
  // Served inline for <img> tags. path.basename + extension whitelist = no traversal;
  // long cache is safe because filenames are content-unique UUIDs (immutable URLs).
  router.get('/api/slideshow-photos/:filename', (req, res) => {
    const fn = path.basename(req.params.filename);
    const ext = fn.split('.').pop().toLowerCase();
    if (!EXT_MIME[ext]) return res.status(400).json({ error: 'Bad filename' });
    const filePath = path.join(SLIDESHOW_DIR, fn);
    if (!fs.existsSync(filePath)) return res.status(404).json({ error: 'Photo not found' });
    res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
    res.type(EXT_MIME[ext]);
    fs.createReadStream(filePath).pipe(res);
  });

  return router;
};
