# Bob's Apps RAG Module - Core indexing pipeline + model singleton

# ====================================================================
# TABLE OF CONTENTS
# ====================================================================
#
#   L   32-41   get_model
#   L   42-54   get_chroma_client
#   L   55-67   get_or_create_collection
#   L   68-76   get_file_type
#   L   77-134  index_document
#   L  135-146  delete_document_chunks
#   L  147-299  index_all_documents
#
# (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
# ====================================================================

import os
import sys
import logging
from sentence_transformers import SentenceTransformer
import chromadb
from rag.chunker import chunk_text

logger = logging.getLogger("rag")

# Singleton — loaded once when module imports
_model = None
_chroma_client = None


def get_model():
    """Load embedding model once at startup, keep in memory."""
    global _model
    if _model is None:
        logger.info("[RAG] Loading embedding model (first time, ~5-10s)...")
        _model = SentenceTransformer('all-MiniLM-L6-v2')
        logger.info("[RAG] Model loaded.")
    return _model


def get_chroma_client():
    """Get persistent ChromaDB client."""
    global _chroma_client
    if _chroma_client is None:
        # Env override first (container deploys mount /data), else the legacy
        # repo-relative location. Keeping both so local dev and Docker share code.
        persist_dir = os.environ.get("CHROMA_DIR") or os.path.join(os.path.dirname(__file__), '..', 'chromadb_data')
        os.makedirs(persist_dir, exist_ok=True)
        logger.info(f"[RAG] ChromaDB persistent storage at {persist_dir}")
        _chroma_client = chromadb.PersistentClient(path=persist_dir)
    return _chroma_client


def get_or_create_collection():
    """Get existing collection or create new one. Handles restarts."""
    client = get_chroma_client()
    try:
        return client.get_collection("document_chunks")
    except Exception:
        logger.info("[RAG] Creating ChromaDB collection 'document_chunks'")
        return client.create_collection(
            "document_chunks",
            metadata={"hnsw:space": "cosine"}  # cosine similarity for semantic search
        )


def get_file_type(filename):
    """Extract file type from filename."""
    if filename.endswith('.pdf'):
        return 'pdf'
    elif filename.endswith('.docx'):
        return 'docx'
    return 'unknown'


def index_document(doc_id, title, filename, text, page_number=None):
    """Index a single document's chunks into ChromaDB.
    
    Args:
        doc_id: Document ID from SQLite
        title: Document title
        filename: Original filename
        text: Extracted text content
        page_number: Optional page number (for PDFs)
        
    Returns:
        Number of chunks created, or 0 if no meaningful text
    """
    model = get_model()
    collection = get_or_create_collection()
    
    # Chunk the text using token-accurate chunking
    chunks = chunk_text(text)
    if not chunks:
        logger.warning(f"No chunks generated for {filename}")
        return 0
    
    # Generate embeddings for ALL chunks at once (batch is faster than loop)
    texts = [c["text"] for c in chunks]
    logger.info(f"[RAG] Generating embeddings for {len(texts)} chunks of {filename}...")
    embeddings = model.encode(texts, show_progress_bar=False).tolist()
    
    # Create deterministic IDs and metadata
    ids = [f"{doc_id}_chunk_{i}" for i in range(len(chunks))]
    metadatas = []
    for i, chunk in enumerate(chunks):
        meta = {
            "doc_id": doc_id,
            "title": title,
            "filename": filename,
            "file_type": get_file_type(filename),
            "chunk_index": chunk["chunk_index"],
            "total_chunks": chunk["total_chunks"],
        }
        if page_number is not None:
            meta["page_number"] = page_number
        metadatas.append(meta)
    
    # Upsert into ChromaDB (upsert handles both create and update)
    try:
        collection.upsert(
            ids=ids,
            embeddings=embeddings,
            documents=texts,  # Store text directly in ChromaDB for retrieval
            metadatas=metadatas
        )
        logger.info(f"[RAG] Indexed {filename}: {len(chunks)} chunks")
        return len(chunks)
    except Exception as e:
        logger.error(f"[RAG] Failed to index {filename} in ChromaDB: {e}")
        raise


def delete_document_chunks(doc_id):
    """Remove all chunks for a document from ChromaDB."""
    collection = get_or_create_collection()
    
    try:
        # Delete by metadata filter (doc_id)
        collection.delete(where={"doc_id": doc_id})
        logger.info(f"[RAG] Deleted chunks for document {doc_id}")
    except Exception as e:
        logger.error(f"[RAG] Failed to delete chunks for {doc_id}: {e}")


def index_all_documents(db_path):
    """Index all unindexed documents from SQLite.
    
    Uses transaction-based error recovery — if one doc fails, 
    the others still succeed and the failed doc stays unindexed.
    
    Args:
        db_path: Path to bobs-apps.db
        
    Returns:
        Dict with indexing stats
    """
    import sqlite3
    
    # Load model once (singleton)
    get_model()
    
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Get all documents that need indexing
    cursor.execute("""
        SELECT id, title, filename, file_type 
        FROM documents 
        WHERE indexed = 0 OR chunk_count IS NULL OR chunk_count = 0
    """)
    all_docs = cursor.fetchall()
    
    if not all_docs:
        logger.info("[RAG] No documents need indexing")
        return {"total": 0, "indexed": 0, "skipped": 0, "failed": 0}
    
    total_indexed = 0
    skipped = 0
    failed = 0
    
    for doc_id, title, filename, file_type in all_docs:
        try:
            # Check if already indexed (skip if chunk_count > 0)
            cursor.execute("SELECT chunk_count FROM documents WHERE id = ?", (doc_id,))
            row = cursor.fetchone()
            if row and row[0] and row[0] > 0:
                logger.info(f"Skipping {filename} (already indexed with {row[0]} chunks)")
                skipped += 1
                continue
            
            # Resolve against DOCS_DIR (same convention as CHROMA_DIR above).
            # The old hardcoded '..'/'documents' path looked inside the code dir,
            # missed /data/docs in the container, and then POISONED the row by
            # marking it indexed — so every later run skipped it. A missing file
            # is a failure to investigate, not an empty document: leave indexed=0.
            from rag.extract_text import extract_text_from_file
            docs_dir = os.environ.get("DOCS_DIR") or os.path.join(os.path.dirname(__file__), '..', 'documents')
            file_path = os.path.join(docs_dir, filename)

            if not os.path.exists(file_path):
                logger.error(f"File not found on disk: {filename} (docs dir: {docs_dir}) — left unindexed")
                failed += 1
                continue
            
            # Extract text with page numbers for PDFs
            result = extract_text_from_file(file_path, title)
            
            if not result or 'text' not in result:
                logger.warning(f"No meaningful text in {filename}, marking as indexed (empty)")
                cursor.execute(
                    "UPDATE documents SET indexed=1, chunk_count=0 WHERE id=?",
                    (doc_id,)
                )
                conn.commit()
                skipped += 1
                continue
            
            text = result['text']
            
            if not text or len(text.strip()) < 100:
                logger.warning(f"Text too short in {filename}, marking as indexed (empty)")
                cursor.execute(
                    "UPDATE documents SET indexed=1, chunk_count=0 WHERE id=?",
                    (doc_id,)
                )
                conn.commit()
                skipped += 1
                continue
            
            # Use transaction for this document's indexing
            cursor.execute("BEGIN TRANSACTION")
            try:
                # For PDFs, we may have multiple pages — index each page separately
                if file_type == 'pdf' and result.get('page_count', 0) > 1:
                    total_chunks = 0
                    for page_num in range(1, result['page_count'] + 1):
                        # Extract text for this specific page
                        from rag.extract_text import extract_page_text
                        page_result = extract_page_text(file_path, title, page_num)
                        if page_result and 'text' in page_result:
                            chunk_count = index_document(
                                doc_id=doc_id,
                                title=title,
                                filename=filename,
                                text=page_result['text'],
                                page_number=page_num
                            )
                            total_chunks += chunk_count
                    
                    cursor.execute(
                        "UPDATE documents SET indexed=1, chunk_count=? WHERE id=?",
                        (total_chunks, doc_id)
                    )
                else:
                    # Single document or DOCX — index all at once
                    chunk_count = index_document(
                        doc_id=doc_id,
                        title=title,
                        filename=filename,
                        text=text
                    )
                    
                    if chunk_count > 0:
                        cursor.execute(
                            "UPDATE documents SET indexed=1, chunk_count=? WHERE id=?",
                            (chunk_count, doc_id)
                        )
                
                conn.commit()
                total_indexed += 1
                
            except Exception as e:
                conn.rollback()
                logger.error(f"Failed to index {filename}: {e}")
                failed += 1
                continue
                
        except Exception as e:
            logger.error(f"Error processing {filename}: {e}")
            failed += 1
            continue
    
    # Update stats
    cursor.execute("SELECT COUNT(*) FROM documents")
    total = cursor.fetchone()[0]
    
    conn.close()
    
    result = {
        "total": total,
        "indexed": total_indexed,
        "skipped": skipped,
        "failed": failed
    }
    
    logger.info(f"[RAG] Indexing complete: {result}")
    return result
