# Bob's Apps RAG Module - Text extraction helpers

# ====================================================================
# TABLE OF CONTENTS
# ====================================================================
#
#   L   24-40   extract_text_from_file
#   L   41-79   extract_page_text
#   L   80-171  _extract_pdf
#   L  172-254  _extract_docx
#   L  255-312  _extract_via_subprocess
#   L  313-321  runs_of
#   L  322-390  para_block
#
# (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
# ====================================================================

import json
import subprocess
import sys
import os


def extract_text_from_file(file_path, title):
    """Extract text from a PDF or DOCX file.

    Dispatches on extension FIRST (the old version tried pymupdf on everything
    whenever it happened to be installed, so .docx files blew up).

    Returns dict with 'title', 'text', 'page_count', and structured 'blocks';
    or None for an unsupported extension. On extraction failure the dict carries
    an 'error' key — callers must check for it.
    """
    if file_path.endswith(".pdf"):
        return _extract_pdf(file_path, title)
    if file_path.endswith(".docx"):
        return _extract_docx(file_path, title)
    return None


def extract_page_text(file_path, title, page_number):
    """Extract text from a specific page of a PDF.
    
    Args:
        file_path: Path to the PDF file
        title: Document title for metadata
        page_number: 1-indexed page number
        
    Returns:
        Dict with 'text' and 'page_count', or None on error
    """
    try:
        import pymupdf
    except ImportError:
        return None
    
    try:
        doc = pymupdf.open(file_path)
        if page_number < 1 or page_number > len(doc):
            return {'text': '', 'page_count': len(doc)}
        
        page = doc[page_number - 1]
        text = page.get_text()
        
        result = {
            'title': title,
            'page_count': len(doc),
            'format': 'structured',
            'blocks': [],
            'text': text.strip()
        }
        
        return result
        
    except Exception as e:
        print(f"Error extracting page {page_number}: {e}", file=sys.stderr, flush=True)
        return {'text': '', 'page_count': 0}


def _extract_pdf(file_path, title):
    """Extract text from PDF using pymupdf."""
    import pymupdf
    
    try:
        doc = pymupdf.open(file_path)
        blocks = []
        
        for page_num in range(len(doc)):
            page = doc[page_num]
            d = page.get_text('dict')
            
            # Calculate median font size for heading detection
            sizes = []
            for block in d.get('blocks', []):
                if block.get('type') != 0:
                    continue
                for line in block.get('lines', []):
                    for span in line.get('spans', []):
                        text = span.get('text', '')
                        if text.strip():
                            sizes.append(span['size'])
            
            median_size = sorted(sizes)[len(sizes) // 2] if sizes else 11.0
            
            # Process blocks with page number tracking
            for block in d.get('blocks', []):
                if block.get('type') != 0:
                    continue
                
                lines = []
                for line in block.get('lines', []):
                    text = ''.join(s['text'] for s in line.get('spans', [])).strip()
                    if not text:
                        continue
                    
                    max_size = max(
                        (s['size'] for s in line.get('spans', [])), 
                        default=median_size
                    )
                    bold = any(
                        ('bold' in (s.get('font') or '').lower()) 
                        for s in line.get('spans', [])
                    )
                    
                    if median_size > 0 and max_size >= median_size * 1.25:
                        level = min(3, int((max_size / median_size - 1) // 0.4) + 1)
                        lines.append({
                            'type': 'heading', 
                            'level': level, 
                            'text': text,
                            'page': page_num + 1
                        })
                    else:
                        lines.append({
                            'type': 'paragraph', 
                            'bold': bold, 
                            'text': text,
                            'page': page_num + 1
                        })
                
                if not lines:
                    continue
                
                first = lines[0]
                if len(lines) == 1 and (first['type'] == 'heading' or first.get('bold')):
                    blocks.append(first)
                else:
                    blocks.append({'type': 'paragraph', 'lines': lines})
        
        # Build plain text for RAG indexing
        plain_text = '\n\n'.join(
            (b.get('text') if b['type'] in ('heading', 'paragraph') and not isinstance(b.get('lines'), list) else
             ' '.join(l['text'] for l in b.get('lines', [])))
            for b in blocks
        )
        
        result = {
            'title': title,
            'page_count': len(doc),
            'format': 'structured',
            'blocks': blocks,
            'text': plain_text.strip()
        }
        
        return result
        
    except Exception as e:
        print(f"Error extracting PDF: {e}", file=sys.stderr, flush=True)
        return {'title': title, 'error': str(e), 'text': ''}


def _extract_docx(file_path, title):
    """Extract text from DOCX using python-docx."""
    import docx
    
    def runs_of(p):
        out = []
        for r in p.runs:
            t = r.text or ''
            if not t.strip():
                continue
            out.append({
                'text': t, 
                'bold': bool(r.bold), 
                'italic': bool(r.italic)
            })
        return out
    
    def para_block(p):
        style = (p.style.name or '').lower() if p.style is not None else ''
        text = p.text.strip()
        if not text:
            return None
        
        if style.startswith('heading'):
            try:
                level = int(''.join(ch for ch in style if ch.isdigit()) or 1)
            except ValueError:
                level = 1
            return {
                'type': 'heading', 
                'level': min(max(level, 1), 4), 
                'text': text
            }
        
        numPr = p._p.find('.//{http://schemas.openxmlformats.org/wordprocessingml/2006/main}numPr')
        if numPr is not None or 'list' in style:
            return {'type': 'list_item', 'runs': runs_of(p)}
        
        return {
            'type': 'paragraph', 
            'runs': runs_of(p) or [
                {'text': text, 'bold': False, 'italic': False}
            ]
        }
    
    try:
        doc = docx.Document(file_path)
        blocks = []
        
        for p in doc.paragraphs:
            b = para_block(p)
            if b is not None:
                blocks.append(b)
        
        # Add tables
        for t in doc.tables:
            rows = [[c.text.strip() for c in row.cells] for row in t.rows]
            if any(any(cell for cell in r) for r in rows):
                blocks.append({'type': 'table', 'rows': rows})
        
        # Build plain text for RAG indexing
        plain_text = '\n\n'.join(
            (b['text'] if b['type'] == 'heading' else
             ''.join(r['text'] for r in b.get('runs', [])) if b['type'] in ('paragraph', 'list_item') else
             ' | '.join(' | '.join(c) for c in b.get('rows', [])))
            for b in blocks
        )
        
        result = {
            'title': title,
            'page_count': 0,
            'format': 'structured',
            'blocks': blocks,
            'text': plain_text.strip()
        }
        
        return result
        
    except Exception as e:
        print(f"Error extracting DOCX: {e}", file=sys.stderr, flush=True)
        return {'title': title, 'error': str(e), 'text': ''}


def _extract_via_subprocess(file_path, title):
    """Fallback extraction using subprocess (existing server.js approach)."""
    from subprocess import run, PIPE
    
    if file_path.endswith('.pdf'):
        script = f"""
import pymupdf, json, sys
file_path, title = sys.argv[1], sys.argv[2]
try:
    doc = pymupdf.open(file_path)
    blocks = []
    for page in doc:
        d = page.get_text('dict')
        sizes = [s['size'] for b in d.get('blocks', []) if b.get('type') == 0
                 for l in b.get('lines', []) for s in l.get('spans', []) if s.get('text', '').strip()]
        median_size = sorted(sizes)[len(sizes) // 2] if sizes else 11.0
        for b in d.get('blocks', []):
            if b.get('type') != 0:
                continue
            lines = []
            for l in b.get('lines', []):
                text = ''.join(s['text'] for s in l.get('spans', [])).strip()
                if not text:
                    continue
                max_size = max((s['size'] for s in l.get('spans', [])), default=median_size)
                bold = any(('bold' in (s.get('font') or '').lower()) for s in l.get('spans', []))
                if median_size > 0 and max_size >= median_size * 1.25:
                    level = min(3, int((max_size / median_size - 1) // 0.4) + 1)
                    lines.append({{'type': 'heading', 'level': level, 'text': text}})
                else:
                    lines.append({{'type': 'paragraph', 'bold': bold, 'text': text}})
            if not lines:
                continue
            first = lines[0]
            if len(lines) == 1 and (first['type'] == 'heading' or first.get('bold')):
                blocks.append(first)
            else:
                blocks.append({{'type': 'paragraph', 'lines': lines}})
    result = {{
        'title': title,
        'page_count': len(doc),
        'format': 'structured',
        'blocks': blocks,
        'text': '\\\\n\\\\n'.join(
            (b.get('text') if b['type'] in ('heading', 'paragraph') and not isinstance(b.get('lines'), list) else
             ' '.join(l['text'] for l in b.get('lines', [])))
            for b in blocks
        )
    }}
    print(json.dumps(result))
except Exception as e:
    print(json.dumps({{'title': title, 'error': str(e)}}))
"""
    elif file_path.endswith('.docx'):
        script = f"""
import docx, json, sys
file_path, title = sys.argv[1], sys.argv[2]

def runs_of(p):
    out = []
    for r in p.runs:
        t = r.text or ''
        if not t.strip():
            continue
        out.append({{'text': t, 'bold': bool(r.bold), 'italic': bool(r.italic)}})
    return out

def para_block(p):
    style = (p.style.name or '').lower() if p.style is not None else ''
    text = p.text.strip()
    if not text:
        return None
    if style.startswith('heading'):
        try:
            level = int(''.join(ch for ch in style if ch.isdigit()) or 1)
        except ValueError:
            level = 1
        return {{'type': 'heading', 'level': min(max(level, 1), 4), 'text': text}}
    numPr = p._p.find('.//{{http://schemas.openxmlformats.org/wordprocessingml/2006/main}}numPr')
    if numPr is not None or 'list' in style:
        return {{'type': 'list_item', 'runs': runs_of(p)}}
    return {{'type': 'paragraph', 'runs': runs_of(p) or [{{'text': text, 'bold': False, 'italic': False}}]}}

try:
    doc = docx.Document(file_path)
    blocks = []
    for p in doc.paragraphs:
        b = para_block(p)
        if b is not None:
            blocks.append(b)
    for t in doc.tables:
        rows = [[c.text.strip() for c in row.cells] for row in t.rows]
        if any(any(cell for cell in r) for r in rows):
            blocks.append({{'type': 'table', 'rows': rows}})
    result = {{
        'title': title,
        'page_count': 0,
        'format': 'structured',
        'blocks': blocks,
        'text': '\\\\n\\\\n'.join(
            (b['text'] if b['type'] == 'heading' else
             ''.join(r['text'] for r in b.get('runs', [])) if b['type'] in ('paragraph', 'list_item') else
             ' | '.join(' | '.join(c) for c in b.get('rows', [])))
            for b in blocks
        )
    }}
    print(json.dumps(result))
except Exception as e:
    print(json.dumps({{'title': title, 'error': str(e)}}))
"""
    else:
        return None
    
    try:
        result = run(
            ['python3', '-c', script, file_path, title],
            capture_output=True,
            text=True,
            timeout=30,
            max_buffer_size=10 * 1024 * 1024
        )
        
        if result.returncode != 0:
            print(f"Subprocess error: {result.stderr}", file=sys.stderr, flush=True)
            return {'title': title, 'error': result.stderr, 'text': ''}
        
        try:
            output = json.loads(result.stdout)
            return output
        except json.JSONDecodeError:
            print(f"Malformed extraction output", file=sys.stderr, flush=True)
            return {'title': title, 'error': 'Malformed output', 'text': ''}
    
    except Exception as e:
        print(f"Subprocess error: {e}", file=sys.stderr, flush=True)
        return {'title': title, 'error': str(e), 'text': ''}
