# Bob's Apps RAG Module - Query pipeline + LLM generation

# ====================================================================
# TABLE OF CONTENTS
# ====================================================================
#
#   L   33-73   build_llm_prompt
#   L   74-109  retrieve_chunks
#   L  110-194  generate_answer
#   L  195-264  query_documents
#   L  265-300  get_query_history
#
# (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
# ====================================================================

import os
import sys
import time
import sqlite3
import requests
from rag.engine import get_model, get_or_create_collection


# LM Studio URL (OpenAI-compatible API)
LM_STUDIO_URL = os.environ.get(
    "LM_STUDIO_URL",
    "http://192.168.0.191:1234/v1/chat/completions"
)

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'bobs-apps.db')


def build_llm_prompt(question, chunks):
    """Build structured prompt with explicit [DOC-N] citations.
    
    Args:
        question: User's question
        chunks: List of chunk dicts from ChromaDB query
        
    Returns:
        Tuple of (system_prompt, user_prompt)
    """
    # Build context with explicit source labels
    context_parts = []
    for i, chunk in enumerate(chunks):
        meta = chunk["metadata"]
        label = f"[DOC-{i+1}: {meta['title']} ({meta['filename']}, chunk {meta['chunk_index']+1}/{meta['total_chunks']})]"
        
        if meta.get('page_number'):
            label += f", page {meta['page_number']}"
        
        context_parts.append(f"{label}\n{chunk['text']}")
    
    context_text = "\n\n".join(context_parts)
    
    system_prompt = """You are a research assistant answering questions using ONLY the provided document snippets. 
Follow these rules:
1. Answer ONLY using the retrieved context. Do not use outside knowledge.
2. If the answer is not in the context, say "I couldn't find information about this in your documents."
3. Cite sources as [DOC-N] at the end of each sentence or claim.
4. Be concise but complete."""
    
    user_prompt = f"""Retrieved context:

{context_text}

Question: {question}

Please answer using the retrieved context and cite your sources with [DOC-N] labels."""
    
    return system_prompt, user_prompt


def retrieve_chunks(query, k=5):
    """Retrieve top-k most similar chunks from ChromaDB.
    
    Args:
        query: User's question text
        k: Number of chunks to retrieve (default 5)
        
    Returns:
        List of chunk dicts with 'text', 'metadata', and 'distance' keys
    """
    model = get_model()
    collection = get_or_create_collection()
    
    # Embed the query using the same singleton model instance
    query_embedding = model.encode([query])[0].tolist()
    
    # Fetch more candidates (k*2) for reranking
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=k * 2,
        include=["documents", "metadatas", "distances"]
    )
    
    chunks = []
    for i in range(len(results["ids"][0])):
        chunks.append({
            "text": results["documents"][0][i],
            "metadata": results["metadatas"][0][i],
            "distance": results["distances"][0][i],  # lower = more similar
        })
    
    # Sort by distance (ascending) and take top k
    chunks.sort(key=lambda c: c["distance"])
    return chunks[:k]


def generate_answer(question, chunks, model=None, max_tokens=None, temperature=None, reasoning_effort=None):
    """Generate LLM answer using retrieved context.
    
    Args:
        question: User's question
        chunks: List of chunk dicts from retrieve_chunks
        model: LM Studio model id, or None/'' for whatever is currently loaded
        
    Returns:
        Dict with 'answer' and 'sources' keys
    """
    # Build prompt
    system_prompt, user_prompt = build_llm_prompt(question, chunks)
    
    try:
        payload = {
            "model": model or "",  # empty = use whatever is loaded in LM Studio
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.3 if temperature is None else temperature,  # low default for factual answers
            # Thinking models spend hidden reasoning against THIS budget (LM Studio
            # reports them as completion_tokens_details.reasoning_tokens). qwen3.6-ud
            # bursts routinely exceed 2048 -> HTTP 200 with content:"" (repro: max_tokens=64
            # returns empty even for a one-word prompt). Headroom beats silent blanks.
            "max_tokens": int(os.environ.get("RAG_MAX_TOKENS", "16384") if max_tokens is None else max_tokens),
        }
        if reasoning_effort:
            # LM Studio honors this on thinking models (tested 'low' on qwen3.6-ud).
            # Only sent when set — unknown top-level keys can upset strict servers.
            payload["reasoning_effort"] = str(reasoning_effort)
        response = requests.post(
            LM_STUDIO_URL,
            json=payload,
            timeout=240  # model spends ~50s reasoning before first token; 60s was too tight
        )
        
        if response.status_code != 200:
            raise Exception(f"LM Studio error {response.status_code}: {response.text[:500]}")
        
        data = response.json()
        choice = (data.get("choices") or [{}])[0]
        answer = (choice.get("message") or {}).get("content")
        if not (answer or "").strip():
            # LM Studio can 200 with empty content when a model is mid-swap or ran out
            # of token budget on hidden reasoning. An empty string here becomes an
            # empty answer in the UI — fail loudly into the offline path instead.
            u = data.get("usage") or {}
            det = u.get("completion_tokens_details") or {}
            raise Exception(
                "empty completion (finish=" + str(choice.get("finish_reason")) +
                ", reasoning_tokens=" + str(det.get("reasoning_tokens")) + ")"
            )
        llm_offline = False

    except Exception as e:
        # LM Studio down or slow — still return the retrieved context, flagged.
        print(f"[RAG] LLM generation failed: {e}", file=sys.stderr, flush=True)
        answer = "LLM was unavailable; here is the retrieved context:" + "\n\n" + "\n\n".join(
            [f"{c['metadata']['title']} (chunk {c['metadata']['chunk_index']+1}): {c['text']}" for c in chunks]
        )
        llm_offline = True
    
    # Format sources for frontend
    sources = []
    for chunk in chunks:
        meta = chunk["metadata"]
        source = {
            "title": meta.get("title", ""),
            "filename": meta.get("filename", ""),
            "chunk_index": meta.get("chunk_index", 0),
            "total_chunks": meta.get("total_chunks", 1),
        }
        if meta.get('page_number'):
            source["page_number"] = meta['page_number']
        sources.append(source)
    
    return {
        "answer": answer,
        "sources": sources,
        "llm_offline": llm_offline
    }


def query_documents(question, model=None, k=None, max_tokens=None,
                    temperature=None, reasoning_effort=None):
    """Main query function: retrieve chunks + generate answer.
    
    Args:
        question: User's question
        
    Returns:
        Dict with 'answer', 'sources', and 'query_time_ms' keys
    """
    start_time = time.time()
    
    # Retrieve relevant chunks
    # retrieval width: caller's k wins over the module default (5)
    chunks = retrieve_chunks(question) if k is None else retrieve_chunks(question, k=int(k))
    
    if not chunks:
        query_time_ms = int((time.time() - start_time) * 1000)
        
        # Log the query to SQLite for debugging
        try:
            conn = sqlite3.connect(DB_PATH)
            cursor = conn.cursor()
            cursor.execute("""
                INSERT INTO rag_queries (id, query_text, results_count, response_time_ms)
                VALUES (?, ?, ?, ?)
            """, [
                f"query_{int(time.time())}",
                question,
                0,
                query_time_ms
            ])
            conn.commit()
            conn.close()
        except Exception as e:
            print(f"[RAG] Failed to log query: {e}", file=sys.stderr, flush=True)
        
        return {
            "answer": "No documents indexed yet. Please index your documents first.",
            "sources": [],
            "query_time_ms": query_time_ms
        }
    
    # Generate answer from retrieved context
    result = generate_answer(question, chunks, model=model, max_tokens=max_tokens,
                             temperature=temperature, reasoning_effort=reasoning_effort)
    query_time_ms = int((time.time() - start_time) * 1000)
    
    # Log the query to SQLite for debugging
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO rag_queries (id, query_text, results_count, response_time_ms)
            VALUES (?, ?, ?, ?)
        """, [
            f"query_{int(time.time())}",
            question,
            len(chunks),
            query_time_ms
        ])
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"[RAG] Failed to log query: {e}", file=sys.stderr, flush=True)
    
    result["query_time_ms"] = query_time_ms
    return result


def get_query_history(limit=20):
    """Get recent queries from SQLite for history display.
    
    Args:
        limit: Maximum number of queries to return
        
    Returns:
        List of query dicts sorted by most recent
    """
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        cursor.execute("""
            SELECT id, query_text, results_count, response_time_ms, created_at
            FROM rag_queries
            ORDER BY created_at DESC
            LIMIT ?
        """, [limit])
        
        queries = []
        for row in cursor.fetchall():
            queries.append({
                "id": row[0],
                "query_text": row[1],
                "results_count": row[2],
                "response_time_ms": row[3],
                "created_at": row[4]
            })
        
        conn.close()
        return queries
        
    except Exception as e:
        print(f"[RAG] Failed to get query history: {e}", file=sys.stderr, flush=True)
        return []
