#!/usr/bin/env python3
"""TOC keeper — enforces the CONTRIBUTING.md rule: lengthy files carry a
FILE SUMMARY + TABLE OF CONTENTS block that stays current with the code.

Usage:
    scripts/gen_toc.py --check        # exit 1 if any tracked file >MIN_LINES has
                                      # no TOC, or a stale one (anchors moved)
    scripts/gen_toc.py --write        # rewrite/insert the TOC block in place
    scripts/gen_toc.py --write path.. # only the named files

Anchor discovery (source of truth for entries):
  * section banners:   `// ── §N: Title` or `# ── §N: Title`
                       `// ==== TITLE ====` / `/* ==== TITLE ==== */`
  * Express routes:    router.get('/x')... once a file has ≥3 of them
  * top-level defs:    JS `function name(` / Python `def name(`/`class Name`
Section banners win when present; otherwise routes, then defs. Line ranges
span each anchor to just before the next one.

Ownership rules (why --write can't wreck a human's file):
  * Blocks we generate carry GENERATED_MARK — only those get replaced.
  * A file with 'TABLE OF CONTENTS' but no GENERATED_MARK is hand-written:
    grandfathered; --check skips it, --write refuses to touch it.
  * Comment style follows the language (.py gets '#', JS/JSX gets '/** */').

Line numbers are rendered against the file WITH the block in place and
re-rendered until nothing moves (update_numbers): any new or resized block
shifts every anchor below it, so one pass is never enough. Rows use fixed
widths, so entry count is what sets height — after the first pass the height
is constant and the loop converges in two or three iterations.

Exit codes: 0 clean, 1 drift found (--check), 2 usage error.
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIN_LINES = 250          # "lengthy" threshold from CONTRIBUTING.md
MAX_ENTRIES = 24         # beyond this the file needs § banners, not a def dump
TOC_RULE = "TABLE OF CONTENTS"
GENERATED_MARK = "generated by scripts/gen_toc.py"  # ownership marker

BANNER_RE = re.compile(r'^\s*(?://|#|/?\*?)\s*(?:──\s*)?(§[\d.]+)\s*:?\s*(.*?)\s*[─=]*\s*$')
EQ_BANNER_RE = re.compile(r'^\s*(?://|/\*)\s*=+\s*(.+?)\s*=+')
JS_DEF_RE = re.compile(r'^(?:export\s+)?(?:async\s+)?function\s+(\w+)')
PY_DEF_RE = re.compile(r'^(?:async\s+)?(?:def|class)\s+(\w+)')
ROUTE_RE = re.compile(r"""^\s*router\.(get|post|patch|put|delete)\(\s*['"]([^'"]+)['"]""")
PY_RULE_RE = re.compile(r'^\s*#\s*=+\s*$')
BLOCK_HEAD_RE = re.compile(r'^(?:/\*\*|(?:#|\*)?\s*=+\s*/?\*?)$')


def tracked_source_files():
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True).stdout
    return [p for p in out.split() if p.endswith((".js", ".jsx", ".py")) and not p.startswith("tests/")]


def is_py(path):
    return path.endswith(".py")


def generated_toc_span(lines):
    """Line span (inclusive) of OUR TOC block, or None. Only closes AFTER
    passing GENERATED_MARK — the opening rule line sits one row below the
    title and would end the span early otherwise. Accepts both closers we've
    ever emitted: '*/' (JS style; earlier versions wrongly wrote these into
    .py files) and a trailing '#' rule line. The span extends UPWARD over the
    block's header rows so a replace removes the whole block — orphan rule
    lines were how --write accumulated cruft on reruns."""
    for i, raw in enumerate(lines):
        if TOC_RULE not in raw:
            continue
        lo = i
        j = i - 1
        while j >= 0 and BLOCK_HEAD_RE.match(lines[j].strip()):
            lo, j = j, j - 1
        for k in range(i + 1, min(i + 80, len(lines))):
            l2 = lines[k].rstrip()
            passed_mark = any(GENERATED_MARK in x for x in lines[i:k])
            if passed_mark and (l2.endswith("*/") or PY_RULE_RE.match(l2)):
                return (lo, k)
        return None  # title found but our mark never appears — not ours
    return None


def collect_anchors(path, lines, mask):
    """All candidate TOC rows with the block's own lines masked out.
    Banners beat Express routes (≥3), routes beat plain defs."""
    pat = PY_DEF_RE if is_py(path) else JS_DEF_RE
    banners, routes, defs = [], [], []
    for i, ln in enumerate(lines):
        if i in mask:
            continue
        if m := BANNER_RE.match(ln):
            num, title = m.group(1), (m.group(2).strip() or "(untitled)")
            banners.append((i, f"{num} {title}"))
        elif m := EQ_BANNER_RE.match(ln):
            banners.append((i, m.group(1).strip()))
        elif m := ROUTE_RE.match(ln):
            routes.append((i, f"{m.group(1).upper():6} {m.group(2)}"))
        elif (m := pat.match(ln)) and not ln.startswith((" ", "\t")):
            defs.append((i, m.group(1)))

    anchors = banners or (routes if len(routes) >= 3 else []) or defs
    # drop anchors that sit above the first line of real code (they'd be prose
    # inside a header comment); if that empties everything, keep what we found
    first_code = next((i for i, ln in enumerate(lines)
                       if i not in mask and ln.strip()
                       and not re.match(r'^\s*(//|#|/?\*|"""|\x27\x27\x27)', ln)), len(lines))
    anchors = [a for a in anchors if a[0] >= first_code] or anchors

    entries, seen = [], set()
    for idx, (ln0, title) in enumerate(anchors):
        nxt = anchors[idx + 1][0] if idx + 1 < len(anchors) else len(lines)
        if title in seen:
            continue  # keep-first dedup; line-bucket keys drifted between passes
        seen.add(title)
        entries.append((ln0 + 1, nxt, title))
    return entries


def render_block(path, entries):
    """The TOC block this tool owns. GENERATED_MARK is what licenses --write
    to replace it; blocks without the mark are left alone. Python files get
    '#' comments — a JS /** */ block there is a syntax error."""
    if len(entries) > MAX_ENTRIES:
        overflow = len(entries) - MAX_ENTRIES
        entries = entries[:MAX_ENTRIES] + [(0, 0, f"… {overflow} more anchors — add § banners")]

    def row(e):
        a, b, title = e
        return f"{{P}}  L{a:>5}-{b:<5}{title}" if (a or b) else f"{{P}}  {'':<13}{title}"

    if is_py(path):
        pre, rows = "#", "\n".join(row(e).replace("{P}", "# ") for e in entries)
        return ("# ====================================================================\n"
                f"# {TOC_RULE}\n"
                "# ====================================================================\n"
                "#\n"
                f"{rows}\n#\n"
                f"# ({GENERATED_MARK} — do not hand-edit line numbers; rerun --write)\n"
                "# ====================================================================")
    rows = "\n".join(row(e).replace("{P}", " *") for e in entries)
    return ("/**\n"
            " * ====================================================================\n"
            f" * {TOC_RULE}\n"
            " * ====================================================================\n"
            " *\n"
            f"{rows}\n"
            " *\n"
            f" * ({GENERATED_MARK} — do not hand-edit line numbers; rerun --write)\n"
            " * ====================================================================\n"
            " */")


def header_end(lines):
    """Line index just after the file's leading shebang and/or its top-of-file
    header — a contiguous run of line comments and/or one block comment — so
    a TOC lands BELOW whatever title/prose the author already put up top."""
    i = 1 if lines and lines[0].startswith("#!") else 0

    def blank_run(j):
        while j < len(lines) and not lines[j].strip():
            j += 1
        return j

    i = blank_run(i)
    moved = True
    while moved:
        moved = False
        if i < len(lines) and re.match(r'^\s*(//|#)', lines[i]):
            while i < len(lines) and (not lines[i].strip() or re.match(r'^\s*(//|#)', lines[i])):
                i += 1
            moved = True
        elif i < len(lines) and lines[i].lstrip().startswith(("/*", '"""')):
            closer = "*/" if lines[i].lstrip().startswith("/*") else '"""'
            for k in range(i + 1, min(i + 80, len(lines))):
                if closer in lines[k]:
                    i = blank_run(k + 1)
                    moved = True
                    break
    return i


def update_numbers(path, text):
    """Replace our existing block with a fresh render whose line numbers are
    TRUE positions in this file (block included). Splices in place; height may
    shift lines below → caller iterates until fixed point. No-op if no block."""
    lines = text.splitlines()
    span = generated_toc_span(lines)
    if not span:
        return text
    mask = set(range(span[0], span[1] + 1))
    block = render_block(path, collect_anchors(path, lines, mask))
    return "\n".join(lines[:span[0]] + block.splitlines() + lines[span[1] + 1:]) + "\n"


def insert_initial(path, text):
    """First-ever TOC for a file: placeholder block at the canonical position;
    update_numbers then fills in real ranges and converges."""
    lines = text.splitlines()
    pos = header_end(lines)
    block = render_block(path, [(0, 0, "(computing…)")])
    pre = [""] if pos and lines[:pos] and lines[pos - 1].strip() else []
    out = lines[:pos] + pre + block.splitlines() + [""] + lines[pos:]
    return "\n".join(out) + "\n"


def converged(path, text):
    """Write to a fixed point. Two forces make one pass insufficient: the
    placeholder→real height shift and in-place row changes both move anchors.
    Row widths are fixed, so after the first real render the block height is
    stable and the loop settles within ~3 iterations."""
    if GENERATED_MARK not in text:
        if TOC_RULE in text:
            return None  # hand-written — grandfathered, caller must skip
        text = insert_initial(path, text)
    prev = None
    cur = update_numbers(path, text)
    n = 0
    while cur != prev and n < 6:
        if GENERATED_MARK not in cur or generated_toc_span(cur.splitlines()) is None:
            break  # sanity: never loop on a file whose block we can't own
        prev, cur, n = cur, update_numbers(path, cur), n + 1
    return cur


def main():
    args = sys.argv[1:]
    mode = next((a for a in args if a in ("--check", "--write")), None)
    explicit = [a for a in args if not a.startswith("--")]
    if mode is None:
        print(__doc__)
        return 2

    files = explicit or tracked_source_files()
    changed, drift = [], []
    for rel in files:
        p = ROOT / rel
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            continue
        if len(text.splitlines()) < MIN_LINES:
            continue

        new = converged(rel, text)
        if new is None:
            continue  # hand-written TOC — grandfathered in both modes

        if mode == "--write":
            if new != text:
                p.write_text(new, encoding="utf-8")
                changed.append(rel)
        elif GENERATED_MARK not in text and TOC_RULE not in text:
            drift.append(f"{rel}: no TOC ({len(text.splitlines())} lines) — run gen_toc.py --write {rel}")
        elif new != text:
            drift.append(f"{rel}: TOC stale (anchors moved or malformed) — rerun gen_toc.py --write {rel}")

    if mode == "--write":
        print("TOC written:" if changed else "nothing changed")
        print(*changed, sep="\n  ")
        return 0
    if drift:
        print("TOC drift:")
        print(*drift, sep="\n")
        return 1
    print(f"OK — every tracked file >{MIN_LINES} lines carries a current generated TOC ({len(files)} scanned)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
