/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   14-388  ASTRO ENGINE APP
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

import React, { useState } from 'react';

// ==================== ASTRO ENGINE APP ====================
// Visual natal chart + data panels. Talks to /api/astro/* (high-precision engine).

const ZODIAC_SYMBOLS = ['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'];
const ASPECT_COLORS = {
  Conjunction: '#e67e22',
  Sextile:     '#2ecc71',
  Square:      '#e74c3c',
  Trine:       '#3498db',
  Opposition:  '#9b59b6'
};

// ── Geometry helpers (SVG, y-down) ───────────────────────────
function polar(cx, cy, r, degCCWFromRight) {
  const rad = degCCWFromRight * Math.PI / 180;
  return { x: cx + r * Math.cos(rad), y: cy - r * Math.sin(rad) };
}

// Screen angle (CCW from right/3-o'clock) for an ecliptic longitude,
// anchored so the Ascendant lands at left (9 o'clock).
function lonToScreen(lon, ascLon) {
  return ((180 + (lon - ascLon)) % 360 + 360) % 360;
}

// ── Chart Wheel SVG ──────────────────────────────────────────
function ChartWheel({ chart }) {
  const SIZE = 520, C = SIZE / 2;
  const R_OUT = 248;   // outer edge of zodiac band
  const R_IN  = 216;   // inner edge of zodiac band (planet ring outside)
  const R_PLANET = 200;
  const R_ASPECT = 178;

  const ascLon = chart.houses.ascendant.longitude;

  // Zodiac sign boundaries: every 30° of longitude
  const signTicks = [];
  for (let i = 0; i < 12; i++) {
    const lonStart = i * 30;
    const a1 = lonToScreen(lonStart, ascLon);
    const p1o = polar(C, C, R_OUT, a1), p1i = polar(C, C, R_IN, a1);
    signTicks.push(
      <line key={`sb${i}`} x1={p1o.x} y1={p1o.y} x2={p1i.x} y2={p1i.y} stroke="#c9ced8" strokeWidth="1.5" />
    );
    // Sign symbol at band center
    const mid = lonToScreen(lonStart + 15, ascLon);
    const ps = polar(C, C, (R_OUT + R_IN) / 2, mid);
    signTicks.push(
      <text key={`ss${i}`} x={ps.x} y={ps.y} textAnchor="middle" dominantBaseline="central" fontSize="17" fill="#5a6070">{ZODIAC_SYMBOLS[i]}</text>
    );
  }

  // Degree ticks every 10° (minor) — subtle
  const degTicks = [];
  for (let d = 0; d < 360; d += 10) {
    if (d % 30 === 0) continue;
    const a = lonToScreen(d, ascLon);
    const p1 = polar(C, C, R_OUT, a), p2 = polar(C, C, R_OUT - 6, a);
    degTicks.push(<line key={`dt${d}`} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} stroke="#dde1e8" strokeWidth="1" />);
  }

  // House cusp lines (Placidus) — from center to inner band edge
  const houseLines = chart.houses.cusps.map((c, i) => {
    if (i === 0 || i === 6) return null; // ASC/DESC drawn as axis line below
    const a = lonToScreen(c.longitude, ascLon);
    const p1 = polar(C, C, R_IN - 2, a), p2 = polar(C, C, 34, a);
    return <line key={`h${i}`} x1={p1.x} y1={p1.y} x2={p2.x} y2={p2.y} stroke="#b8bfcc" strokeWidth="1.5" />;
  });

  // ASC/DESC axis (horizontal) and MC/IC axis (vertical)
  const ascAxis = [
    <line key="ax-h" x1={C - R_OUT} y1={C} x2={C + R_OUT} y2={C} stroke="#8a93a5" strokeWidth="1.5" />,
    <line key="ax-v" x1={C} y1={C - R_OUT} x2={C} y2={C + R_OUT} stroke="#8a93a5" strokeWidth="1.5" />
  ];

  // House numbers at cusp positions (just inside band)
  const houseNums = chart.houses.cusps.map((c, i) => {
    const a = lonToScreen(c.longitude + 2.5, ascLon);
    const p = polar(C, C, R_IN - 14, a);
    return <text key={`hn${i}`} x={p.x} y={p.y} textAnchor="middle" dominantBaseline="central" fontSize="10" fill="#8a93a5">{i + 1}</text>;
  });

  // Planet placement with collision offset (stack outward if crowded)
  const planets = Object.values(chart.planets);
  const sorted = [...planets].sort((a, b) => a.longitude - b.longitude);
  const placed = [];
  for (const p of sorted) {
    let ring = R_PLANET;
    // Check against already-placed: if within 14° angular distance at same ring, push out
    for (let guard = 0; guard < 3; guard++) {
      const crowded = placed.some(q => {
        const dLon = Math.abs(((q.longitude - p.longitude) % 360 + 540) % 360 - 180);
        return dLon < 14 && q.ring === ring;
      });
      if (!crowded) break;
      ring -= 16;
    }
    placed.push({ ...p, ring });
  }

  const planetGlyphs = placed.map(p => {
    const a = lonToScreen(p.longitude, ascLon);
    const pos = polar(C, C, p.ring, a);
    return (
      <g key={p.name}>
        <text x={pos.x} y={pos.y} textAnchor="middle" dominantBaseline="central" fontSize="19" fontWeight="600" fill="#2c3140">
          {p.symbol}{p.retrograde ? '℞' : ''}
        </text>
      </g>
    );
  });

  // Aspect lines between planet positions (use placed rings)
  const aspectLines = chart.aspects.map((asp, i) => {
    const p1 = placed.find(p => p.name === asp.body1);
    const p2 = placed.find(p => p.name === asp.body2);
    if (!p1 || !p2) return null;
    // Only draw tighter aspects to avoid spaghetti (orb < 6°)
    if (asp.orb > 6) return null;
    const a1 = lonToScreen(p1.longitude, ascLon), a2 = lonToScreen(p2.longitude, ascLon);
    const q1 = polar(C, C, R_ASPECT, a1), q2 = polar(C, C, R_ASPECT, a2);
    return <line key={`al${i}`} x1={q1.x} y1={q1.y} x2={q2.x} y2={q2.y} stroke={ASPECT_COLORS[asp.name]} strokeWidth="1.4" opacity="0.75" />;
  });

  // ASC / MC labels
  const ascLabel = polar(C, C, R_OUT + 16, lonToScreen(ascLon, ascLon));
  const mcLabel = { x: C, y: C - R_OUT - 14 };

  return (
    <svg viewBox={`0 0 ${SIZE} ${SIZE}`} style={{ width: '100%', maxWidth: SIZE, display: 'block', margin: '0 auto' }}>
      {/* Rings */}
      <circle cx={C} cy={C} r={R_OUT} fill="#ffffff" stroke="#8a93a5" strokeWidth="2" />
      <circle cx={C} cy={C} r={R_IN} fill="#fbfcfe" stroke="#c9ced8" strokeWidth="1.5" />
      <circle cx={C} cy={C} r={R_ASPECT - 14} fill="none" stroke="#eef0f4" strokeWidth="1" />

      {degTicks}
      {signTicks}
      {ascAxis}
      {houseLines}
      {aspectLines}
      {planetGlyphs}
      {houseNums}

      <text x={ascLabel.x} y={ascLabel.y} textAnchor="middle" dominantBaseline="central" fontSize="12" fontWeight="700" fill="#4a5163">ASC</text>
      <text x={mcLabel.x} y={mcLabel.y} textAnchor="middle" dominantBaseline="central" fontSize="12" fontWeight="700" fill="#4a5163">MC</text>

      {/* Center date */}
      <text x={C} y={C - 8} textAnchor="middle" fontSize="11" fill="#8a93a5">{chart.chart.date.slice(0, 10)}</text>
      <text x={C} y={C + 8} textAnchor="middle" fontSize="11" fill="#8a93a5">Placidus</text>
    </svg>
  );
}

// ── Location search (city name or US ZIP) ────────────────────
// Server proxies Nominatim at /api/astro/geocode; this component only renders
// the ranked matches. Results are buttons, not a typeahead list — keep it dumb.
function LocationSearch({ onPick }) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState(null); // null = no search yet
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  function search() {
    const q = query.trim();
    if (q.length < 2) return;
    setLoading(true);
    setError('');
    fetch(`/api/astro/geocode?q=${encodeURIComponent(q)}`)
      .then(r => r.json().then(d => ({ ok: r.ok, d })))
      .then(({ ok, d }) => {
        if (!ok) { setError(d.error || 'Geocoding failed'); setResults(null); }
        else if (d.results.length === 0) { setError(`No matches for “${q}”`); setResults(null); }
        else setResults(d.results);
      })
      .catch(err => setError(String(err)))
      .finally(() => setLoading(false));
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 4, minWidth: 200 }}>
      <label style={fieldStyle}>Location (city or US ZIP)
        <span style={{ display: 'flex', gap: 6 }}>
          <input
            type="text"
            value={query}
            placeholder="Denver, or 90210…"
            onChange={e => setQuery(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); search(); } }}
            style={{ ...inputStyle, width: 170 }}
          />
          <button className="btn btn-ghost" onClick={search} disabled={loading || query.trim().length < 2}>
            {loading ? '…' : 'Find'}
          </button>
        </span>
      </label>
      {error && <span style={{ fontSize: 11.5, color: '#a94442' }}>{error}</span>}
      {results && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
          {results.map(r => (
            <button
              key={`${r.lat},${r.lon},${r.displayName}`}
              onClick={() => { onPick(r); setResults(null); setQuery(r.name); }}
              title={`${r.lat}, ${r.lon}`}
              style={{
                textAlign: 'left', fontSize: 12, padding: '4px 8px', cursor: 'pointer',
                background: '#eef3fb', border: '1px solid #cdd9ee', borderRadius: 6, color: '#2c3140'
              }}
            >📍 {r.displayName}</button>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Main App Component ───────────────────────────────────────
export default function AstroEngine() {
  const [date, setDate] = useState('1990-06-15');
  const [time, setTime] = useState('14:30');
  const [lat, setLat] = useState(40.7128);
  const [lon, setLon] = useState(-74.006);
  const [place, setPlace] = useState('');   // display name from the last location pick
  const [tz, setTz] = useState('');         // IANA zone; '' keeps time fields UTC (legacy behavior)
  const [chart, setChart] = useState(null);

  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  function calculate() {
    setLoading(true);
    setError('');
    const tzParam = tz ? `&tz=${encodeURIComponent(tz)}` : '';
    fetch(`/api/astro/chart?date=${encodeURIComponent(date)}&time=${encodeURIComponent(time)}&lat=${lat}&lon=${lon}${tzParam}`)
      .then(r => r.json().then(d => ({ ok: r.ok, d })))
      .then(({ ok, d }) => {
        if (!ok) setError(d.error || 'Calculation failed');
        else setChart(d);
        setLoading(false);
      })
      .catch(err => { setError(String(err)); setLoading(false); });
  }

  function useToday() {
    const now = new Date();
    if (tz) {
      // Local wall-clock: what the user's watch says, matching tz= semantics.
      const parts = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric', month: '2-digit', day: '2-digit' }).format(now);
      const hm = new Intl.DateTimeFormat('en-GB', { timeZone: tz, hour: '2-digit', minute: '2-digit', hour12: false }).format(now);
      setDate(parts); setTime(hm);
    } else {
      setDate(now.toISOString().slice(0, 10));
      setTime(`${String(now.getUTCHours()).padStart(2,'0')}:${String(now.getUTCMinutes()).padStart(2,'0')}`);
    }
  }

  // Human-readable zone note under the time field: shows the live UTC offset.
  let tzNote = 'UTC';
  if (tz) {
    try {
      const z = new Intl.DateTimeFormat('en-US', { timeZone: tz, timeZoneName: 'shortOffset' })
        .formatToParts(new Date(`${date}T${time || '12:00'}Z`)).find(p => p.type === 'timeZoneName');
      tzNote = `${tz.replace(/_/g, ' ')} (${z ? z.value.replace('GMT', 'UTC') : '?'})`;
    } catch { tzNote = tz; }
  }

  return (
    <div>
      {/* Input form */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px', alignItems: 'flex-end', marginBottom: '20px' }}>
        <label style={fieldStyle}>Date
          <input type="date" value={date} onChange={e => setDate(e.target.value)} style={inputStyle} />
        </label>
        <label style={fieldStyle}>Time ({tzNote})
          <input type="time" value={time} onChange={e => setTime(e.target.value)} style={inputStyle} />
        </label>
        <label style={fieldStyle}>Latitude
          <input type="number" step="0.0001" value={lat} onChange={e => { setLat(parseFloat(e.target.value) || 0); setPlace(''); setTz(''); }} style={{ ...inputStyle, width: '90px' }} />
        </label>
        <label style={fieldStyle}>Longitude
          <input type="number" step="0.0001" value={lon} onChange={e => { setLon(parseFloat(e.target.value) || 0); setPlace(''); setTz(''); }} style={{ ...inputStyle, width: '90px' }} />
        </label>
        <LocationSearch onPick={r => { setLat(r.lat); setLon(r.lon); setPlace(r.displayName); setTz(r.timezone || ''); }} />
        <button className="btn btn-primary" onClick={calculate} disabled={loading}>
          {loading ? 'Calculating…' : '✦ Calculate Chart'}
        </button>
        <button className="btn btn-ghost" onClick={useToday}>Use today</button>
      </div>
      {chart && place && (
        <p style={{ color: '#6b7080', fontSize: '12.5px', margin: '-12px 0 14px' }}>📍 {place}{tz ? ` — time entered as local (${tz})` : ''}</p>
      )}

      {error && (
        <div style={{ background: '#fdecec', border: '1px solid #f5c6cb', color: '#a94442', borderRadius: '8px', padding: '10px 14px', marginBottom: '16px' }}>
          {error}
        </div>
      )}

      {!chart && !error && (
        <p style={{ color: '#6b7080', fontSize: '13px' }}>
          Enter a birth date, time and location to generate a natal chart. Positions are computed with an arcsecond-precision ephemeris (VSOP87). Find your birthplace by city or ZIP and the time becomes local — including historical DST. Leave lat/lon manual for UTC entry.
        </p>
      )}

      {chart && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '24px' }}>
          {/* Wheel */}
          <div style={{ flex: '1 1 380px', minWidth: 320, background: '#fff', border: '1px solid #e5e8ee', borderRadius: '12px', padding: '16px' }}>
            <ChartWheel chart={chart} />
          </div>

          {/* Data panels */}
          <div style={{ flex: '1 1 340px', minWidth: 300, display: 'flex', flexDirection: 'column', gap: '16px' }}>
            {/* Planets table */}
            <div className="panel" style={{ padding: '14px' }}>
              <h4 style={sectionTitle}>Planetary Positions</h4>
              <table style={tableStyle}>
                <thead>
                  <tr><th>Body</th><th>Sign</th><th>Degree</th><th>Retro</th></tr>
                </thead>
                <tbody>
                  {Object.values(chart.planets).map(p => (
                    <tr key={p.name}>
                      <td style={{ fontWeight: 600 }}>{p.symbol} {p.name}</td>
                      <td>{p.signName}</td>
                      <td>{p.display.replace(/^[^\s]+\s/, '')}</td>
                      <td>{p.retrograde ? '℞' : ''}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Houses */}
            <div className="panel" style={{ padding: '14px' }}>
              <h4 style={sectionTitle}>Houses (Placidus)</h4>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '6px', fontSize: '12.5px' }}>
                {chart.houses.cusps.map((c, i) => (
                  <div key={i} style={{ background: '#f7f8fa', borderRadius: '6px', padding: '5px 8px' }}>
                    <span style={{ color: '#8a93a5' }}>{i + 1}</span> {c.symbol} {Math.floor(c.degreesInSign)}°{String(Math.floor((c.degreesInSign % 1) * 60)).padStart(2, '0')}'
                  </div>
                ))}
              </div>
            </div>

            {/* Aspects */}
            <div className="panel" style={{ padding: '14px' }}>
              <h4 style={sectionTitle}>Aspects ({chart.aspects.length})</h4>
              <div style={{ maxHeight: '200px', overflowY: 'auto', fontSize: '12.5px' }}>
                {chart.aspects.map((a, i) => (
                  <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '3px 0', borderBottom: '1px solid #f0f2f5' }}>
                    <span>
                      <span style={{ color: ASPECT_COLORS[a.name], fontWeight: 700 }}>{a.symbol1}{a.symbol}{a.symbol2}</span>{' '}
                      {a.body1} {a.name.toLowerCase()} {a.body2}
                    </span>
                    <span style={{ color: '#8a93a5' }}>{a.orb}° orb</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Summary */}
            <div className="panel" style={{ padding: '14px', background: '#f7f8fa' }}>
              <h4 style={sectionTitle}>Summary</h4>
              <pre style={{ margin: 0, fontSize: '12.5px', whiteSpace: 'pre-wrap', fontFamily: 'inherit', color: '#3c4254' }}>{chart.summary}</pre>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

const fieldStyle = { display: 'flex', flexDirection: 'column', gap: '4px', fontSize: '12px', color: '#6b7080' };
const inputStyle = { padding: '7px 10px', border: '1px solid #d5dae3', borderRadius: '8px', fontSize: '13.5px', background: '#fff', color: '#2c3140' };
const sectionTitle = { margin: '0 0 10px', fontSize: '13px', fontWeight: 700, color: '#4a5163' };
const tableStyle = { width: '100%', borderCollapse: 'collapse', fontSize: '12.5px' };
