/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   19-45   DOCUMENT REPOSITORY APP
 *  L   46-156  STRUCTURED PREVIEW RENDERER
 *  L  157-271  PDF RENDER PREVIEW
 *  L  272-1059 READ-ALOUD (Kokoro TTS, speechSynthesis fallback)
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

import React, { useState, useEffect, useRef } from 'react';
import { apiFetch, apiUrl } from '../api';
import { splitSpeechChunks } from '../tts-chunks';

// ==================== DOCUMENT REPOSITORY APP ====================

const UPLOAD_MIME = {
  pdf: 'application/pdf',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
};

function formatFileSize(bytes) {
  if (!bytes || bytes === 0) return '';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

function formatDate(dateStr) {
  if (!dateStr) return '';
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { 
      year: 'numeric', month: 'short', day: 'numeric' 
    });
  } catch {
    return dateStr;
  }
}

// ==================== STRUCTURED PREVIEW RENDERER ====================

function RunText({ run }) {
  const style = {};
  if (run.bold) style.fontWeight = 700;
  if (run.italic) style.fontStyle = 'italic';
  return <span style={style}>{run.text}</span>;
}

const HEADING_STYLES = {
  1: { fontSize: '24px', fontWeight: 700, margin: '28px 0 12px 0', color: '#1a1a2e' },
  2: { fontSize: '20px', fontWeight: 700, margin: '24px 0 10px 0', color: '#1a1a2e' },
  3: { fontSize: '17px', fontWeight: 600, margin: '20px 0 8px 0', color: '#1a1a2e' },
  4: { fontSize: '15px', fontWeight: 600, margin: '16px 0 6px 0', color: '#374151' }
};

function PreviewBlock({ block }) {
  if (block.type === 'heading') {
    const style = HEADING_STYLES[block.level] || HEADING_STYLES[4];
    return <div style={style}>{block.text}</div>;
  }
  
  if (block.type === 'paragraph' && Array.isArray(block.lines)) {
    // PDF paragraph: lines may carry per-line heading/bold info
    return (
      <p style={{ margin: '0 0 12px 0', fontSize: '14px', lineHeight: 1.7, color: '#374151' }}>
        {block.lines.map((line, i) => (
          <span key={i}>
            {i > 0 && ' '}
            {line.type === 'heading' ? (
              <strong style={{ fontWeight: 700 }}>{line.text}</strong>
            ) : line.bold ? (
              <strong>{line.text}</strong>
            ) : (
              line.text
            )}
          </span>
        ))}
      </p>
    );
  }
  
  if ((block.type === 'paragraph' || block.type === 'list_item') && Array.isArray(block.runs)) {
    const isList = block.type === 'list_item';
    return (
      <div style={{
        margin: isList ? '2px 0 2px 8px' : '0 0 12px 0',
        paddingLeft: isList ? '18px' : 0,
        position: 'relative',
        fontSize: '14px', lineHeight: 1.7, color: '#374151'
      }}>
        {isList && <span style={{ position: 'absolute', left: 0, color: '#6b7080' }}>•</span>}
        {block.runs.map((run, i) => <RunText key={i} run={run} />)}
      </div>
    );
  }
  
  if (block.type === 'table') {
    return (
      <div style={{ margin: '16px 0', overflowX: 'auto' }}>
        <table style={{ borderCollapse: 'collapse', width: '100%', fontSize: '13px' }}>
          <tbody>
            {block.rows.map((row, ri) => (
              <tr key={ri}>
                {row.map((cell, ci) => (
                  <td key={ci} style={{
                    border: '1px solid #d1d5db', padding: '6px 10px',
                    fontWeight: ri === 0 ? 700 : 400,
                    backgroundColor: ri === 0 ? '#f3f4f6' : '#fff',
                    color: '#374151', textAlign: 'left'
                  }}>
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }
  
  return null;
}

function PreviewContent({ data }) {
  if (data.error) {
    return <p style={{ color: '#dc2626' }}>[Error: {data.error}]</p>;
  }
  
  // Structured blocks (preferred) — preserves headings, bold/italic, lists, tables
  if (Array.isArray(data.blocks) && data.blocks.length > 0) {
    return (
      <div>
        {data.blocks.map((block, i) => <PreviewBlock key={i} block={block} />)}
      </div>
    );
  }
  
  // Fallback: plain text extraction
  const maxLen = 50000;
  const text = data.text || '';
  return (
    <pre style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0, fontFamily: 'inherit' }}>
      {text.length > maxLen 
        ? text.substring(0, maxLen) + '\n\n... [truncated, ' + (text.length - maxLen).toLocaleString() + ' more characters]'
        : text}
    </pre>
  );
}

// ==================== PDF RENDER PREVIEW ====================
// Two rendering paths, chosen by what the browser can actually do:
//   * Native viewer (desktop Chrome/Firefox/Edge): fetch bytes into an
//     application/pdf blob URL and iframe it. An iframe pointed straight at
//     /docs/<file> shows a download prompt — that route answers
//     Content-Disposition: attachment (it is the download endpoint).
//   * pdf.js canvas renderer (Android Chrome has NO PDF plugin, iOS is flaky):
//     lazily import pdfjs-dist and paint each page to a canvas. The native stub
//     there renders an "Open" dead-end button instead of pages.
// navigator.pdfViewerEnabled === false is the honest feature-detect for "iframe
// will not work here".

function shouldUseCanvasPdf({ pdfViewerEnabled, isSmallScreen }) {
  // pdfViewerEnabled is undefined on ancient browsers — assume desktop-ish native.
  if (pdfViewerEnabled === false) return true;
  // Small touch screens get the canvas path even where a viewer nominally exists:
  // blob-URL viewers ignore viewport width and pinch-zoom fights the modal.
  return isSmallScreen;
}

function PdfPreviewFrame({ url, title }) {
  return (
    <iframe
      title={`PDF preview: ${title}`}
      src={url}
      style={{ width: '100%', height: 'calc(85vh - 126px)', border: 'none', borderRadius: 8, backgroundColor: '#525659' }}
    />
  );
}

// Which pane the modal body shows (pure so the smoke test can assert it without a DOM):
// the renderer wins for PDFs whenever a blob is loaded and the user hasn't flipped to
// text; everything else — docx, failed fetch, toggled mode — falls back to extracted text.
function previewViewFor(fileType, blobUrl, mode) {
  return fileType === 'pdf' && blobUrl && mode === 'render' ? 'render' : 'text';
}

// Viewport-width hook — mobile modal is full-screen and PDFs switch to canvas
// rendering below this breakpoint. matchMedia so rotation/resizes re-evaluate.
const SMALL_SCREEN_QUERY = '(max-width: 700px)';
function useIsSmallScreen() {
  const [small, setSmall] = useState(
    () => typeof window !== 'undefined' && !!window.matchMedia?.(SMALL_SCREEN_QUERY).matches
  );
  useEffect(() => {
    if (typeof window === 'undefined' || !window.matchMedia) return;
    const mq = window.matchMedia(SMALL_SCREEN_QUERY);
    const onChange = (e) => setSmall(e.matches);
    mq.addEventListener('change', onChange);
    return () => mq.removeEventListener('change', onChange);
  }, []);
  return small;
}

// pdf.js renderer: paints every page to a canvas inside one scrollable column.
// Used where the native iframe viewer is absent or useless (Android Chrome,
// small screens). pdfjs-dist (~1MB) is dynamically imported so the desktop path
// never downloads it. `url` may be a blob: URL — fetch stays in-memory.
function PdfJsPages({ url, onError }) {
  const containerRef = useRef(null);

  useEffect(() => {
    let cancelled = false;
    const el = containerRef.current;
    if (!el) return undefined;

    (async () => {
      try {
        const [pdfjs, workerUrl] = await Promise.all([
          import('pdfjs-dist'),
          import('pdfjs-dist/build/pdf.worker.min.mjs?url').then(m => m.default),
        ]);
        if (cancelled) return;
        pdfjs.GlobalWorkerOptions.workerSrc = workerUrl;

        const pdf = await pdfjs.getDocument({ url }).promise;
        const cssWidth = Math.max(280, el.clientWidth - 16);
        const dpr = Math.min(window.devicePixelRatio || 1, 2);

        for (let n = 1; n <= pdf.numPages && !cancelled; n++) {
          const page = await pdf.getPage(n);
          const base = page.getViewport({ scale: 1 });
          const cssScale = cssWidth / base.width;
          const viewport = page.getViewport({ scale: cssScale });

          const canvas = document.createElement('canvas');
          canvas.style.cssText = 'display:block;width:100%;height:auto;margin:0 auto 8px auto;border-radius:4px;box-shadow:0 1px 4px rgba(0,0,0,0.35);background:#fff';
          canvas.width = Math.floor(viewport.width * dpr);
          canvas.height = Math.floor(viewport.height * dpr);
          el.appendChild(canvas);

          // Render at device resolution: ctx scale × viewport scale stacks.
          const ctx = canvas.getContext('2d');
          ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
          await page.render({ canvasContext: ctx, viewport }).promise;
        }

        if (!cancelled) pdf.cleanup?.();
      } catch (e) {
        // Cancellation on unmount is expected; anything else → caller falls back to text.
        if (!cancelled && !e?.name?.includes('Abort') && String(e?.message || '').indexOf('Cancelled') === -1) {
          onError(e);
        }
      }
    })();

    return () => {
      cancelled = true;
      el.replaceChildren(); // drop canvases + free bitmaps on unmount
    };
  }, [url, onError]);

  return <div ref={containerRef} style={{ padding: '8px' }} />;
}

// ==================== READ-ALOUD (Kokoro TTS, speechSynthesis fallback) ======

const SPEED_OPTIONS = [0.8, 1.0, 1.2, 1.5];
const TTS_SETTINGS_KEY = 'document-tts-settings-v1'; // voice + speed, per browser (do NOT reuse the RAG settings key)

function loadTtsSettings() {
  try {
    const raw = JSON.parse(localStorage.getItem(TTS_SETTINGS_KEY) || '{}');
    return {
      voice: typeof raw.voice === 'string' ? raw.voice : '',
      speed: SPEED_OPTIONS.includes(raw.speed) ? raw.speed : 1.0,
    };
  } catch { return { voice: '', speed: 1.0 }; }
}
function saveTtsSettings(s) {
  try { localStorage.setItem(TTS_SETTINGS_KEY, JSON.stringify(s)); } catch {}
}

/**
 * Read-aloud player. Primary path: /api/tts/synth per chunk → mp3 blob → <audio>
 * playlist with prefetch (chunk i+1 fetched while i plays). Fallback path when
 * the TTS service is unreachable: legacy speechSynthesis, whole text as one
 * utterance (with its Chrome stall-nudge quirk kept — only on this path).
 *
 * `supported` stays true if either engine exists; mode flips to 'fallback' per
 * document after a synth failure or voices-fetch 503.
 */
function useReadAloud() {
  const [speaking, setSpeaking] = useState(false);
  const [paused, setPaused] = useState(false);
  const [progress, setProgress] = useState(null); // {index, total} while speaking (TTS path)
  const [voices, setVoices] = useState([]);        // Kokoro voice ids; [] until fetched
  const [ttsAvailable, setTtsAvailable] = useState(true); // false after voices/synth failure → fallback UI hint
  const [voice, setVoiceState] = useState(() => loadTtsSettings().voice); // '' = engine default
  const [speed, setSpeedState] = useState(() => loadTtsSettings().speed);

  const audioRef = useRef(null);          // single <audio> element, created lazily
  const cancelPlayRef = useRef(null);     // resolves the play-promise when stop() fires mid-play
  const urlsRef = useRef([]);             // object URLs to revoke on stop (pdfBlobUrl discipline)
  const tokenRef = useRef(0);             // invalidates in-flight fetches/cbs after stop/new play
  const browserVoicesRef = useRef([]);    // speechSynthesis voices (fallback path)

  const browserSupported = typeof window !== 'undefined' && 'speechSynthesis' in window;
  const supported = true; // TTS engine always attemptable; failures degrade to fallback/offline error

  function revokeUrls() {
    for (const u of urlsRef.current) URL.revokeObjectURL(u);
    urlsRef.current = [];
  }

  function stop() {
    tokenRef.current++;
    if (audioRef.current) { audioRef.current.pause(); audioRef.current.src = ''; }
    if (browserSupported) window.speechSynthesis.cancel();
    revokeUrls();
    // Release a playTts frozen mid-await; its token check then exits silently.
    if (cancelPlayRef.current) { const c = cancelPlayRef.current; cancelPlayRef.current = null; c(); }
    setSpeaking(false);
    setPaused(false);
    setProgress(null);
    stopNudge(); // hoisted function decl below; clears the fallback stall interval
  }

  // Fetch one chunk's mp3 as an object URL. Throws on any failure — caller decides.
  async function synthChunk(text, token) {
    const res = await apiFetch('/api/tts/synth', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, ...(voice ? { voice } : {}), speed }),
    });
    if (!res.ok) throw new Error(`tts synth HTTP ${res.status}`);
    if (tokenRef.current !== token) throw new Error('cancelled'); // body arrived after stop
    const url = URL.createObjectURL(await res.blob());
    urlsRef.current.push(url);
    return url;
  }

  // Plays the chunk playlist. Returns when done or cancelled; any synth/playback
  // failure routes to onTtsFailure (which stops + flips availability). One-deep
  // prefetch: while chunk i plays, chunk i+1 is being fetched; at most two blob
  // URLs exist per document beyond what's already queued, revoked together on stop.
  async function playTts(chunks) {
    const token = ++tokenRef.current;
    setSpeaking(true);
    setPaused(false);
    if (!audioRef.current) audioRef.current = new Audio();
    const audio = audioRef.current;

    const cancelled = () => tokenRef.current !== token;
    let prefetch = null; // Promise<string>|null for the NEXT chunk; errors surface at consume time

    for (let i = 0; i < chunks.length; i++) {
      let url;
      try {
        url = prefetch ? await prefetch : await synthChunk(chunks[i], token);
      } catch (e) {
        if (!cancelled() && e.message !== 'cancelled') onTtsFailure();
        return;
      }
      if (cancelled()) return;

      prefetch = i + 1 < chunks.length ? synthChunk(chunks[i + 1], token) : null;
      if (prefetch) prefetch.catch(() => {}); // avoid unhandled rejection while playing; consumed next loop

      const playedOk = await new Promise((resolve) => {
        // Element event PROPERTIES (not addEventListener): repeated plays must
        // replace, never stack, handlers on the shared <audio> element.
        const cleanup = () => { audio.onended = null; audio.onerror = null; cancelPlayRef.current = null; };
        const finish = (ok) => { cleanup(); resolve(ok); };
        audio.onended = () => finish(true);
        audio.onerror = () => finish(false);
        cancelPlayRef.current = () => finish(true); // stop(): token already bumped → loop exits quietly
        audio.src = url;
        // Speed is baked into the synth request (server-side), so keep the element neutral.
        if (cancelled()) return finish(true);
        audio.play().catch(() => finish(false));
      });

      if (cancelled()) return; // stop()/re-speak during play or pause — its state wins
      if (!playedOk) { onTtsFailure(); return; }
      setProgress({ index: i + 1, total: chunks.length });
    }
    revokeUrls();
    setSpeaking(false);
    setPaused(false);
    setProgress(null);
  }

  function onTtsFailure() {
    setTtsAvailable(false);
    stop();
  }

  // ---- fallback engine ------------------------------------------------------
  const [fallbackMode, setFallbackMode] = useState(false);

  function pickBrowserVoice() {
    // Prefer Edge/Chrome "Natural"/"Neural" online voices — dramatically better than legacy.
    const list = browserVoicesRef.current.length ? browserVoicesRef.current : window.speechSynthesis.getVoices();
    return list.find(v => /natural|neural/i.test(v.name)) || null;
  }

  function speakFallback(text) {
    if (!browserSupported) { setTtsAvailable(false); return; }
    window.speechSynthesis.cancel();
    const token = ++tokenRef.current;
    const u = new SpeechSynthesisUtterance(text);
    const bv = pickBrowserVoice();
    if (bv) u.voice = bv;
    u.rate = speed;
    u.onstart = () => { if (tokenRef.current === token) { setSpeaking(true); setPaused(false); } };
    u.onend = () => { if (tokenRef.current === token) { setSpeaking(false); setPaused(false); stopNudge(); } };
    u.onerror = (e) => { if (tokenRef.current === token && e.error !== 'canceled') { setSpeaking(false); setPaused(false); stopNudge(); } };
    window.speechSynthesis.speak(u);
    startNudge(token);
  }

  // Chrome quirk (fallback path only): long utterances stall after ~15s —
  // nudge with a periodic pause/resume. The TTS path doesn't need it: chunks are short.
  const nudgeRef = useRef(null);
  function startNudge(token) {
    stopNudge();
    nudgeRef.current = setInterval(() => {
      if (tokenRef.current !== token) return stopNudge();
      const ss = window.speechSynthesis;
      if (ss.speaking && !ss.paused) { ss.pause(); ss.resume(); }
    }, 12000);
  }
  function stopNudge() {
    if (nudgeRef.current) { clearInterval(nudgeRef.current); nudgeRef.current = null; }
  }

  // voices fetch doubles as availability probe; speechSynthesis voice list warms the fallback.
  useEffect(() => {
    let onVoicesChanged = null;
    if (browserSupported) {
      onVoicesChanged = () => { browserVoicesRef.current = window.speechSynthesis.getVoices(); };
      onVoicesChanged();
      window.speechSynthesis.addEventListener?.('voiceschanged', onVoicesChanged);
    }
    let cancelled = false;
    apiFetch('/api/tts/voices').then(async (r) => {
      if (!r.ok) throw new Error('unavailable');
      const d = await r.json();
      if (!cancelled) setVoices(Array.isArray(d.voices) ? d.voices : []);
    }).catch(() => { if (!cancelled) setTtsAvailable(false); });
    return () => {
      cancelled = true;
      stop(); // unmount: kill audio + revoke URLs (also covers preview-close via parent effect)
      stopNudge();
      if (onVoicesChanged) window.speechSynthesis.removeEventListener?.('voiceschanged', onVoicesChanged);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Speak the whole speech text; engine choice is internal. A live session is
  // replaced in place (stop() bumps the token, which cancels playTts cleanly).
  async function speak(text) {
    if (!text) return;
    stop();
    if (ttsAvailable) {
      const chunks = splitSpeechChunks(text);
      if (chunks.length === 0) return;
      setFallbackMode(false);
      await playTts(chunks); // failures land in onTtsFailure; cancel lands here silently
      return;
    }
    setFallbackMode(true);
    speakFallback(text);
  }

  function togglePause() {
    if (fallbackMode && browserSupported) {
      if (paused) { window.speechSynthesis.resume(); setPaused(false); }
      else if (speaking) { window.speechSynthesis.pause(); setPaused(true); }
      return;
    }
    const a = audioRef.current;
    if (!a) return;
    if (paused) { a.play().catch(() => {}); setPaused(false); }
    else if (speaking) { a.pause(); setPaused(true); }
  }

  function setVoice(v) { setVoiceState(v); saveTtsSettings({ voice: v, speed }); }
  function setSpeed(s) { setSpeedState(s); saveTtsSettings({ voice, speed: s }); }

  return {
    supported, speaking, paused, progress,
    voices, voice, ttsAvailable, fallbackMode,
    speed, speak, stop, togglePause, setVoice, setSpeed,
  };
}

// Convert structured blocks to natural spoken text (tables as "column: value")
function blocksToSpeechText(blocks) {
  const parts = [];
  for (const b of blocks) {
    if (b.type === 'heading') {
      parts.push(b.text);
    } else if ((b.type === 'paragraph' || b.type === 'list_item') && Array.isArray(b.runs)) {
      parts.push(b.runs.map(r => r.text).join(''));
    } else if (b.type === 'paragraph' && Array.isArray(b.lines)) {
      parts.push(b.lines.map(l => l.text).join(' '));
    } else if (b.type === 'table') {
      const [header, ...rows] = b.rows;
      for (const row of rows) {
        const cells = header.map((h, i) => `${h}: ${row[i] || ''}`).filter(c => !c.endsWith(': '));
        if (cells.length) parts.push(cells.join('. '));
      }
    }
  }
  return parts.filter(Boolean).join(' ');
}

function DocumentRepository() {
  const [docs, setDocs] = useState([]);
  const [categories, setCategories] = useState([]);
  const [search, setSearch] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [previewDoc, setPreviewDoc] = useState(null);
  const [previewData, setPreviewData] = useState(null); // extracted text/blocks (docx preview + read-aloud)
  const [pdfBlobUrl, setPdfBlobUrl] = useState(null);   // raw PDF bytes → inline renderer
  const [previewMode, setPreviewMode] = useState('render'); // 'render' | 'text' toggle for PDFs
  const [pdfRenderError, setPdfRenderError] = useState(false); // canvas renderer blew up → text fallback
  const [loading, setLoading] = useState(true);
  const previewTokenRef = useRef(0); // guards against a slow fetch landing on a newer preview
  const isSmallScreen = useIsSmallScreen();
  const ra = useReadAloud();

  // Release blob URLs as soon as the preview switches or closes — otherwise every
  // open keeps a full PDF alive in memory until the tab dies.
  useEffect(() => () => { if (pdfBlobUrl) URL.revokeObjectURL(pdfBlobUrl); }, [pdfBlobUrl]);

  // Stop read-aloud whenever the preview closes or switches documents (or unmounts).
  useEffect(() => {
    return () => ra.stop();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [previewDoc]);

  function startReadAloud() {
    const text = previewData && Array.isArray(previewData.blocks) && previewData.blocks.length
      ? blocksToSpeechText(previewData.blocks)
      : (previewData && previewData.text) || '';
    if (!text.trim()) return;
    ra.speak(text);
  }
  const [error, setError] = useState('');

  // Upload form state (kept out of the global error banner — inline feedback)
  const [upFile, setUpFile] = useState(null);
  const [upTitle, setUpTitle] = useState('');
  const [upCategory, setUpCategory] = useState('general');
  const [uploading, setUploading] = useState(false);
  const uploadInputRef = useRef(null);

  async function handleUpload() {
    if (!upFile) { setError('Choose a .pdf or .docx file first'); return; }
    const ext = upFile.name.toLowerCase().endsWith('.pdf') ? 'pdf' : 'docx';
    if (!upFile.name.toLowerCase().endsWith('.' + ext)) {
      setError('Only .pdf and .docx files are supported'); return;
    }
    setUploading(true); setError('');
    try {
      const params = new URLSearchParams({ title: upTitle.trim() || upFile.name.replace(/\.[^.]+$/, '') });
      if (upCategory && upCategory !== 'general') params.set('category', upCategory);
      const res = await fetch(apiUrl(`/api/docs/upload?${params}`), {
        method: 'POST',
        headers: { 'Content-Type': UPLOAD_MIME[ext] },
        body: upFile, // raw bytes; server names it <uuid>.<ext> and computes size
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error((data && data.error) || `HTTP ${res.status}`);
      setUpFile(null); setUpTitle(''); setUpCategory('general');
      if (uploadInputRef.current) uploadInputRef.current.value = '';
      await loadDocs(); // refresh grid from server — single source of truth
    } catch (e) {
      setError(e.message);
    } finally {
      setUploading(false);
    }
  }

  // Load documents from API
  useEffect(() => {
    loadDocs();
  }, []);

  async function loadDocs() {
    try {
      setLoading(true);
      // Build query string conditionally — URLSearchParams({key: undefined})
      // would serialize the literal string "undefined" into the URL
      const params = new URLSearchParams();
      if (search) params.set('search', search);
      if (selectedCategory !== 'all') params.set('category', selectedCategory);
      const qs = params.toString();
      const res = await apiFetch('/api/docs' + (qs ? '?' + qs : ''));
      
      if (!res.ok) throw new Error('Failed to load documents');
      
      const data = await res.json();
      setDocs(data.docs || []);
      setCategories(data.categories || []);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  // Debounced search
  useEffect(() => {
    const timer = setTimeout(loadDocs, 300);
    return () => clearTimeout(timer);
  }, [search, selectedCategory]);

  async function handlePreview(doc) {
    const myToken = ++previewTokenRef.current;
    setPreviewDoc(doc);
    setPreviewData(null);
    setPdfBlobUrl(null);
    setPreviewMode('render');
    setPdfRenderError(false);

    // Text extraction and raw bytes are independent — fire both. Extraction still
    // powers docx previews and read-aloud; the blob powers inline PDF rendering.
    const textP = apiFetch(`/api/docs/${doc.id}/preview`)
      .then(res => res.ok ? res.json() : Promise.reject(new Error('Failed to load preview')))
      .catch(e => ({ error: e.message }));

    let blobP = Promise.resolve(null);
    if (doc.file_type === 'pdf') {
      blobP = apiFetch(`/docs/${encodeURIComponent(doc.filename)}`)
        .then(res => res.ok ? res.blob() : Promise.reject(new Error(`HTTP ${res.status}`)))
        .then(blob => URL.createObjectURL(new Blob([blob], { type: 'application/pdf' })))
        .catch(() => null); // renderer unavailable — modal falls back to extracted text
    }

    const [textData, blobUrl] = await Promise.all([textP, blobP]);
    if (myToken !== previewTokenRef.current) {
      // A newer preview opened while we were fetching — drop this payload and its blob.
      if (blobUrl) URL.revokeObjectURL(blobUrl);
      return;
    }
    setPreviewData(textData);
    if (blobUrl) {
      setPdfBlobUrl(blobUrl);
    } else if (doc.file_type === 'pdf') {
      setPreviewMode('text'); // no bytes → don't show an empty renderer pane
    }
  }

  async function handleDelete(doc) {
    if (!window.confirm('Delete this document?')) return;
    
    try {
      const res = await apiFetch(`/api/docs/${doc.id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error('Failed to delete');
      
      // Server already removed the file from disk — just update local state
      setDocs(prev => prev.filter(d => d.id !== doc.id));
    } catch (e) {
      alert(e.message);
    }
  }

  function getDocIcon(fileType) {
    return fileType === 'pdf' ? '📕' : '📘';
  }

  // Filtered docs (client-side for instant search feedback)
  const filteredDocs = docs; // Already filtered server-side

  const previewView = previewDoc ? previewViewFor(previewDoc.file_type, pdfBlobUrl, previewMode) : 'text';
  // Android/Chrome (no PDF plugin) and small screens paint pages with pdf.js.
  // If that renderer fails we degrade to the text pane rather than a dead iframe stub.
  const canvasPdf = shouldUseCanvasPdf({
    pdfViewerEnabled: typeof navigator !== 'undefined' ? navigator.pdfViewerEnabled : undefined,
    isSmallScreen,
  });
  const showRenderPane = previewView === 'render' && !(canvasPdf && pdfRenderError);

  if (loading && docs.length === 0) {
    return (
      <div style={{ textAlign: 'center', padding: '40px' }}>
        <p>Loading documents...</p>
      </div>
    );
  }

  return (
    <div className="doc-repo">
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <h3 style={{ fontSize: '18px', fontWeight: 600, color: '#1a1a2e', margin: '0 0 16px 0' }}>
          📄 Document Repository
        </h3>
        
        {/* Search and filter bar */}
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', alignItems: 'center' }}>
          <input
            type="text"
            placeholder="Search documents..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            style={{
              flex: 1, minWidth: '200px', padding: '8px 12px',
              border: '1px solid #d1d5db', borderRadius: '6px',
              fontSize: '14px', outline: 'none'
            }}
          />
          
          <select
            value={selectedCategory}
            onChange={(e) => setSelectedCategory(e.target.value)}
            style={{
              padding: '8px 12px', border: '1px solid #d1d5db',
              borderRadius: '6px', fontSize: '14px', outline: 'none',
              backgroundColor: '#fff'
            }}
          >
            <option value="all">All Categories</option>
            {categories.map(cat => (
              <option key={cat} value={cat}>{cat}</option>
            ))}
          </select>
        </div>

        {/* Upload form */}
        <div style={{
          display: 'flex', gap: '8px', flexWrap: 'wrap', alignItems: 'center',
          marginTop: '12px', padding: '12px', backgroundColor: '#f9fafb',
          border: '1px dashed #d1d5db', borderRadius: '8px'
        }}>
          <input
            ref={uploadInputRef}
            type="file"
            accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            onChange={(e) => { setUpFile(e.target.files[0] || null); setError(''); }}
            style={{ fontSize: '13px', maxWidth: '260px' }}
          />
          <input
            type="text"
            placeholder={upFile ? upFile.name.replace(/\.[^.]+$/, '') : 'Title (optional)'}
            value={upTitle}
            onChange={(e) => setUpTitle(e.target.value)}
            style={{
              flex: 1, minWidth: '160px', padding: '8px 12px',
              border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '14px', outline: 'none'
            }}
          />
          <input
            type="text"
            placeholder="Category (optional)"
            value={upCategory === 'general' ? '' : upCategory}
            onChange={(e) => setUpCategory(e.target.value.trim() || 'general')}
            style={{
              width: '160px', padding: '8px 12px',
              border: '1px solid #d1d5db', borderRadius: '6px', fontSize: '14px', outline: 'none'
            }}
          />
          <button
            onClick={handleUpload}
            disabled={!upFile || uploading}
            style={{
              padding: '8px 16px', fontSize: '14px', fontWeight: 600,
              backgroundColor: (!upFile || uploading) ? '#c7d2fe' : '#4f46e5',
              color: '#fff', border: 'none', borderRadius: '6px',
              cursor: (!upFile || uploading) ? 'not-allowed' : 'pointer'
            }}
          >
            {uploading ? 'Uploading...' : '⬆ Upload'}
          </button>
        </div>

        {/* Stats */}
        <p style={{ color: '#6b7080', fontSize: '13px', margin: '12px 0 0 0' }}>
          {docs.length} document{docs.length !== 1 ? 's' : ''} stored
        </p>
      </div>

      {/* Error state */}
      {error && (
        <div style={{ padding: '16px', backgroundColor: '#fef2f2', border: '1px solid #fecaca', borderRadius: '8px', color: '#dc2626', marginBottom: '16px' }}>
          Error: {error}
        </div>
      )}

      {/* Empty state */}
      {!loading && docs.length === 0 && !error && (
        <div style={{ textAlign: 'center', padding: '60px 20px', color: '#6b7080' }}>
          <p style={{ fontSize: '48px', marginBottom: '16px' }}>📄</p>
          <h4 style={{ margin: '0 0 8px 0', color: '#374151' }}>No documents yet</h4>
          <p style={{ fontSize: '14px', maxWidth: '400px', margin: '0 auto' }}>
            Ask Hermes to create a report or document and it will be stored here. 
            You can browse, preview, and download them from this app.
          </p>
        </div>
      )}

      {/* Document grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '16px' }}>
        {filteredDocs.map(doc => (
          <div key={doc.id} style={{
            border: '1px solid #e5e7eb', borderRadius: '12px', padding: '16px',
            backgroundColor: '#fff', transition: 'box-shadow 0.2s'
          }}
          onMouseEnter={(e) => { e.currentTarget.style.boxShadow = '0 4px 12px rgba(0,0,0,0.08)'; }}
          onMouseLeave={(e) => { e.currentTarget.style.boxShadow = 'none'; }}
          >
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
              <span style={{ fontSize: '32px', flexShrink: 0 }}>{getDocIcon(doc.file_type)}</span>
              
              <div style={{ flex: 1, minWidth: 0 }}>
                <h4 style={{ margin: '0 0 4px 0', fontSize: '15px', fontWeight: 600, color: '#1a1a2e' }}>
                  {doc.title}
                </h4>
                
                {doc.description && (
                  <p style={{ margin: '0 0 8px 0', fontSize: '13px', color: '#6b7080', lineHeight: '1.4' }}>
                    {doc.description.length > 120 
                      ? doc.description.substring(0, 120) + '...' 
                      : doc.description}
                  </p>
                )}

                <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap', marginBottom: '8px' }}>
                  {doc.category && doc.category !== 'general' && (
                    <span style={{
                      fontSize: '11px', padding: '2px 8px', borderRadius: '10px',
                      backgroundColor: '#eef2ff', color: '#4f46e5', fontWeight: 500
                    }}>
                      {doc.category}
                    </span>
                  )}
                  <span style={{
                    fontSize: '11px', padding: '2px 8px', borderRadius: '10px',
                    backgroundColor: '#f3f4f6', color: '#6b7080'
                  }}>
                    {doc.file_type.toUpperCase()}
                  </span>
                </div>

                <p style={{ margin: '0 0 12px 0', fontSize: '12px', color: '#9ca3af' }}>
                  {formatDate(doc.created_at)}{doc.file_size ? ' · ' + formatFileSize(doc.file_size) : ''}
                </p>

                <div style={{ display: 'flex', gap: '8px' }}>
                  <button
                    onClick={() => handlePreview(doc)}
                    style={{
                      flex: 1, padding: '6px 12px', fontSize: '13px',
                      backgroundColor: '#4f46e5', color: '#fff', border: 'none',
                      borderRadius: '6px', cursor: 'pointer'
                    }}
                  >
                    👁 Preview
                  </button>
                  
                  <a
                    href={apiUrl(`/docs/${doc.filename}`)}
                    download={doc.filename}
                    style={{
                      flex: 1, padding: '6px 12px', fontSize: '13px', textAlign: 'center',
                      backgroundColor: '#f0fdf4', color: '#16a34a', border: 'none',
                      borderRadius: '6px', cursor: 'pointer', textDecoration: 'none'
                    }}
                  >
                    ⬇ Download
                  </a>

                  <button
                    onClick={() => handleDelete(doc)}
                    style={{
                      padding: '6px 10px', fontSize: '13px',
                      backgroundColor: '#fef2f2', color: '#dc2626', border: 'none',
                      borderRadius: '6px', cursor: 'pointer'
                    }}
                  >
                    🗑
                  </button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Preview Modal — full-bleed on phones, floating card above */}
      {previewDoc && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center',
          justifyContent: 'center', zIndex: 1000, padding: isSmallScreen ? 0 : '20px'
        }}
        onClick={() => setPreviewDoc(null)}
        >
          <div style={{
            backgroundColor: '#fff', borderRadius: isSmallScreen ? 0 : '16px',
            maxWidth: '800px', width: '100%', height: isSmallScreen ? '100%' : undefined,
            maxHeight: isSmallScreen ? undefined : '85vh',
            display: 'flex', flexDirection: 'column'
          }}
          onClick={(e) => e.stopPropagation()}
          >
            {/* Modal header */}
            <div style={{
              padding: isSmallScreen ? '10px 12px' : '16px 20px',
              borderBottom: '1px solid #e5e7eb',
              display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px'
            }}>
              <h4 style={{ margin: 0, fontSize: '16px', fontWeight: 600, color: '#1a1a2e', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                {previewDoc.title}
              </h4>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                {/* Renderer/text toggle — only meaningful once a PDF's bytes are in hand */}
                {previewDoc.file_type === 'pdf' && pdfBlobUrl && (
                  <div style={{ display: 'flex', border: '1px solid #d1d5db', borderRadius: '6px', overflow: 'hidden', flexShrink: 0 }}>
                    {[['render', isSmallScreen ? '📄' : '📄 Render'], ['text', isSmallScreen ? '📝' : '📝 Text']].map(([mode, label]) => (
                      <button
                        key={mode}
                        onClick={() => setPreviewMode(mode)}
                        title={mode === 'render' ? 'Rendered pages' : 'Extracted text'}
                        style={{
                          padding: isSmallScreen ? '6px 10px' : '4px 10px', fontSize: '12px', border: 'none', cursor: 'pointer',
                          backgroundColor: previewView === mode ? '#4f46e5' : '#fff',
                          color: previewView === mode ? '#fff' : '#374151'
                        }}
                      >
                        {label}
                      </button>
                    ))}
                  </div>
                )}
                {/* Read-aloud controls — TTS player with browser-voice fallback */}
                <>
                  {(ra.speaking || ra.paused) ? (
                    <>
                      <button
                        onClick={ra.togglePause}
                        title={ra.paused ? 'Resume reading aloud' : 'Pause reading aloud'}
                        style={{ padding: '4px 10px', fontSize: '13px', backgroundColor: '#eef2ff', color: '#4f46e5', border: 'none', borderRadius: '6px', cursor: 'pointer' }}
                      >
                        {ra.paused ? '▶ Resume' : '⏸ Pause'}
                      </button>
                      <button
                        onClick={ra.stop}
                        title="Stop reading aloud"
                        style={{ padding: '4px 10px', fontSize: '13px', backgroundColor: '#fef2f2', color: '#dc2626', border: 'none', borderRadius: '6px', cursor: 'pointer' }}
                      >
                        ⏹ Stop{ra.progress ? ` ${ra.progress.index}/${ra.progress.total}` : ''}
                      </button>
                    </>
                  ) : (
                    <button
                      onClick={startReadAloud}
                      title="Read this document aloud"
                      style={{ padding: '4px 10px', fontSize: '13px', backgroundColor: '#f0fdf4', color: '#16a34a', border: 'none', borderRadius: '6px', cursor: 'pointer' }}
                    >
                      🔊 Read Aloud
                    </button>
                  )}
                  {ra.ttsAvailable && ra.voices.length > 0 && (
                    <select
                      value={ra.voice}
                      onChange={(e) => ra.setVoice(e.target.value)}
                      title="Kokoro voice"
                      style={{ padding: '4px 6px', fontSize: '12px', border: '1px solid #d1d5db', borderRadius: '6px', backgroundColor: '#fff', color: '#374151', maxWidth: '130px' }}
                    >
                      <option value="">Default voice</option>
                      {ra.voices.map(v => <option key={v.id} value={v.id}>{v.id}</option>)}
                    </select>
                  )}
                  {!ra.ttsAvailable && (
                    <span title="Kokoro TTS service unreachable — using the browser voice instead"
                          style={{ fontSize: '11px', color: '#b45309' }}>browser voice</span>
                  )}
                  <select
                    value={ra.speed}
                    onChange={(e) => ra.setSpeed(parseFloat(e.target.value))}
                    title="Reading speed"
                    style={{ padding: '4px 6px', fontSize: '12px', border: '1px solid #d1d5db', borderRadius: '6px', backgroundColor: '#fff', color: '#374151' }}
                  >
                    {SPEED_OPTIONS.map(s => <option key={s} value={s}>{s === 1 ? '1×' : `${s}×`}</option>)}
                  </select>
                </>
                <button
                  onClick={() => setPreviewDoc(null)}
                  style={{
                    padding: '4px 12px', fontSize: '18px', backgroundColor: 'transparent',
                    border: 'none', cursor: 'pointer', color: '#6b7080'
                  }}
                >
                  ×
                </button>
              </div>
            </div>

            {/* Preview content — PDFs render as real pages (iframe on desktop,
                pdf.js canvases where no usable viewer exists); everything else
                shows extracted text */}
            <div style={showRenderPane && !canvasPdf ? { flexShrink: 0 } : {
              padding: '20px', overflowY: 'auto', flex: 1, minHeight: 0,
              fontSize: '14px', lineHeight: '1.6', color: '#374151'
            }}>
              {showRenderPane ? (
                canvasPdf ? (
                  <PdfJsPages url={pdfBlobUrl} onError={() => setPdfRenderError(true)} />
                ) : (
                  <PdfPreviewFrame url={pdfBlobUrl} title={previewDoc.title} />
                )
              ) : previewData && previewView === 'render' ? (
                // canvas renderer failed mid-preview → degrade to extracted text
                <PreviewContent data={previewData} />
              ) : previewData ? (
                <PreviewContent data={previewData} />
              ) : (
                <p>Loading preview...</p>
              )}
            </div>

            {/* Modal footer */}
            <div style={{
              padding: isSmallScreen ? '10px 12px' : '12px 20px', borderTop: '1px solid #e5e7eb',
              display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '8px'
            }}>
              <span style={{ fontSize: '13px', color: '#6b7080' }}>
                {previewDoc.file_type.toUpperCase()} · {formatDate(previewDoc.created_at)}
              </span>
              <a
                href={apiUrl(`/docs/${previewDoc.filename}`)}
                download={previewDoc.filename}
                style={{
                  padding: '8px 16px', fontSize: '14px', backgroundColor: '#4f46e5',
                  color: '#fff', borderRadius: '6px', textDecoration: 'none', whiteSpace: 'nowrap'
                }}
              >
                ⬇ Download Full Document
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default DocumentRepository;
