/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   27-65   MarkdownAnswer
 *  L   66-75   Field
 *  L   76-578  RagSettings
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

/**
 * Renders an assistant answer as GitHub-flavored markdown.
 *
 * Deliberately NO rehype-raw: raw HTML in LLM output stays escaped text, so a
 * document that manipulates the model into emitting <script>/onerror markup
 * can't execute here. react-markdown's default urlTransform also strips
 * javascript:/data: hrefs. Links open in a new tab (rel=noopener).
 * Only assistant messages use this — user text is never treated as markup.
 */
function MarkdownAnswer({ content }) {
  return (
    <div className="rag-md">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        components={{
          a: ({ node, ...props }) => (
            <a {...props} target="_blank" rel="noopener noreferrer" />
          ),
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
}

const MD_CSS = `
.rag-md > :first-child { margin-top: 0; }
.rag-md > :last-child { margin-bottom: 0; }
.rag-md p, .rag-md ul, .rag-md ol { margin: 8px 0; }
.rag-md ul, .rag-md ol { padding-left: 22px; }
.rag-md li { margin: 3px 0; }
.rag-md h1, .rag-md h2, .rag-md h3, .rag-md h4 { margin: 14px 0 6px; font-size: 1.05em; color: #2d3748; }
.rag-md code { background: #eef1f5; padding: 1px 5px; border-radius: 4px; font-size: 0.92em; }
.rag-md pre { background: #1a2340; color: #e2e8f0; padding: 10px 12px; border-radius: 6px; overflow-x: auto; margin: 10px 0; }
.rag-md pre code { background: none; padding: 0; color: inherit; font-size: 0.88em; }
.rag-md blockquote { margin: 10px 0; padding: 4px 12px; border-left: 3px solid #cbd5e0; color: #4a5568; }
.rag-md table { border-collapse: collapse; margin: 10px 0; font-size: 0.95em; }
.rag-md th, .rag-md td { border: 1px solid #cbd5e0; padding: 4px 10px; }
.rag-md th { background: #edf2f7; }
.rag-md hr { border: none; border-top: 1px solid #e2e8f0; margin: 12px 0; }
`;
import { apiFetch } from '../api';

// Collapsible generation-settings panel. Empty field = omit from request = server/env default,
// which keeps this UI honest about what's actually being overridden.
const inputStyle = { width: '100%', padding: '6px 8px', fontSize: '13px', border: '1px solid #e2e8f0', borderRadius: '6px' };
// Module scope on purpose: defining it inside the component remounts children per keystroke (focus loss).
function Field({ label, hint, children }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', minWidth: '150px', flex: 1 }}>
      <label style={{ fontSize: '11px', fontWeight: 600, color: '#4a5568' }}>{label}</label>
      {children}
      {hint && <span style={{ fontSize: '11px', color: '#a0aec0' }}>{hint}</span>}
    </div>
  );
}

function RagSettings({ settings, onChange }) {
  return (
    <div style={{ padding: '12px 16px', background: '#f8f9fa', borderRadius: '8px', border: '1px solid #e2e8f0' }}>
      <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
        <Field label="Context chunks (k)" hint="default 5 — more context, slower + pricier prompts">
          <input type="number" min="1" max="20" value={settings.k ?? ''} placeholder="5"
            onChange={(e) => { const v = e.target.value; onChange({ k: v === '' ? null : Math.max(1, Math.min(20, parseInt(v, 10) || 5)) }); }}
            style={inputStyle} />
        </Field>
        <Field label="Max tokens" hint="default 16384 — thinking models spend hidden reasoning against this">
          <input type="number" min="256" max="65536" step="256" value={settings.maxTokens} placeholder="16384"
            onChange={(e) => onChange({ maxTokens: e.target.value.replace(/[^\d]/g, '') })}
            style={inputStyle} />
        </Field>
        <Field label="Temperature" hint="default 0.3 — 0=deterministic, 2=wild">
          <input type="number" min="0" max="2" step="0.1" value={settings.temperature} placeholder="0.3"
            onChange={(e) => onChange({ temperature: e.target.value.replace(/[^\d.]/g, '') })}
            style={inputStyle} />
        </Field>
        <Field label="Reasoning effort" hint="for thinking models; blank = model default">
          <select value={settings.reasoningEffort} onChange={(e) => onChange({ reasoningEffort: e.target.value })} style={inputStyle}>
            <option value="">(default)</option>
            <option value="low">low</option>
            <option value="medium">medium</option>
            <option value="high">high</option>
          </select>
        </Field>
      </div>
    </div>
  );
}

export default function DocumentRAG() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState(null);
  const [models, setModels] = useState([]);       // LM Studio ids + load state from /api/rag/models
  const [model, setModel] = useState('');          // '' = whatever LM Studio has loaded
  const warmTimerRef = useRef(null);               // poll timer for load-state refresh
  const messagesEndRef = useRef(null);

  // Chat sessions. activeId is remembered per-browser (localStorage) so a reload lands
  // back in the thread you were reading; sessions themselves live server-side. null id
  // = unsaved draft: nothing appears in the sidebar until its first message succeeds.
  const SESSION_KEY = 'bobs-apps.rag.session';
  const [sessions, setSessions] = useState([]);
  const [activeId, setActiveId] = useState(() => {
    try { return localStorage.getItem(SESSION_KEY) || null; } catch { return null; }
  });
  const [confirmDeleteId, setConfirmDeleteId] = useState(null); // two-step delete per row

  function refreshSessions() {
    apiFetch('/api/rag/sessions')
      .then(r => (r.ok ? r.json() : { sessions: [] }))
      .then(d => setSessions(d.sessions || []))
      .catch(() => {});
  }

  // Generation settings (gear menu). Persisted per-browser; server clamps every value.
  const SETTINGS_KEY = 'bobs-apps.rag.settings';
  const DEFAULT_SETTINGS = { k: null, maxTokens: '', temperature: '', reasoningEffort: '' };
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settings, setSettings] = useState(() => {
    try { return { ...DEFAULT_SETTINGS, ...JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}') }; }
    catch { return DEFAULT_SETTINGS; }
  });
  function updateSettings(patchObj) {
    setSettings(prev => {
      const next = { ...prev, ...patchObj };
      try { localStorage.setItem(SETTINGS_KEY, JSON.stringify(next)); } catch { /* private mode: session-only */ }
      return next;
    });
  }

  // Load status + model list on mount; load session list and restore the last thread too.
  useEffect(() => {
    refreshSessions();
    if (activeId) openSession(activeId);
    apiFetch('/api/rag/status')
      .then(r => r.json())
      .then(data => setStatus(data))
      .catch(err => console.error('Failed to load RAG status:', err));
    apiFetch('/api/rag/models')
      .then(r => (r.ok ? r.json() : { models: [] }))
      .then(data => setModels(data.models || []))
      .catch(() => setModels([]));  // LM Studio down: dropdown just doesn't show
    return () => clearInterval(warmTimerRef.current);  // never leak a poller past unmount
  }, []);

  const refreshModels = () => {
    apiFetch('/api/rag/models')
      .then(r => (r.ok ? r.json() : { models: [] }))
      .then(d => setModels(d.models || []))
      .catch(() => {});
  };

  // Kick a server-side warm request, then poll load state every ~6s until loaded.
  // Without this your first question after picking an unloaded model paid the full
  // multi-minute disk load inside the query timeout and died as "Query failed".
  const warmModel = (id) => {
    clearInterval(warmTimerRef.current);
    if (!id) return;
    apiFetch('/api/rag/models/warm', {
      method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: id }),
    }).catch(() => {});  // fire-and-forget; poller below reflects reality regardless
    warmTimerRef.current = setInterval(() => {
      apiFetch('/api/rag/models')
        .then(r => (r.ok ? r.json() : { models: [] }))
        .then(d => {
          const list = d.models || [];
          setModels(list);
          // Stop as soon as THE picked model reports loaded — not just "something loaded".
          if (list.some(m => m.id === id && m.state === 'loaded')) clearInterval(warmTimerRef.current);
        })
        .catch(() => {});  // LM Studio briefly unreachable mid-load; keep polling anyway
    }, 6000);
  };

  // Auto-scroll to bottom of messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  async function handleQuery(e) {
    e.preventDefault();
    if (!input.trim() || loading) return;

    const userMessage = input.trim();
    setInput('');
    
    // Add user message to chat
    setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setLoading(true);

    try {
      // Draft session? Create the server row now (not at "New chat" click) so unused
      // drafts never appear in the sidebar.
      let sessionId = activeId;
      if (!sessionId) {
        const cr = await apiFetch('/api/rag/sessions', { method: 'POST' });
        if (!cr.ok) throw new Error(`session create failed HTTP ${cr.status}`);
        sessionId = (await cr.json()).id;
        setActiveId(sessionId);
        try { localStorage.setItem(SESSION_KEY, sessionId); } catch { /* ignore */ }
      }

      const response = await apiFetch('/api/rag/query', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          query: userMessage,
          model,
          session_id: sessionId,
          // empty-string knobs are omitted entirely -> server/env defaults apply
          options: Object.fromEntries(Object.entries({
            k: settings.k == null ? '' : String(settings.k),
            max_tokens: settings.maxTokens,
            temperature: settings.temperature,
            reasoning_effort: settings.reasoningEffort
          }).filter(([, v]) => String(v).trim() !== ''))
        })
      });

      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      
      const data = await response.json();
      
      // Add assistant message with answer and sources
      setMessages(prev => [...prev, { 
        role: 'assistant', 
        content: data.answer || 'No answer generated.',
        sources: data.sources || [],
        model: model || null,           // show which model answered (empty = server default)
        llm_offline: !!data.llm_offline
      }]);
      refreshSessions();  // first answer titled the thread / bumped its sort order
    } catch (err) {
      console.error('Query failed:', err);
      setMessages(prev => [...prev, { 
        role: 'assistant', 
        content: `Error: ${err.message}`,
        error: true
      }]);
    } finally {
      setLoading(false);
    }
  }

  async function handleIndex() {
    setStatus({ ...status, indexing: true });
    
    try {
      const response = await apiFetch('/api/rag/index', { method: 'POST' });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      
      const data = await response.json();
      console.log('Indexing result:', data);
      
      // Refresh status after indexing
      const statusResp = await apiFetch('/api/rag/status');
      const newData = await statusResp.json();
      setStatus(newData);
    } catch (err) {
      console.error('Indexing failed:', err);
    } finally {
      setStatus(prev => ({ ...prev, indexing: false }));
    }
  }

  // Switch threads: fetch its messages and remember it for the next reload.
  function openSession(id) {
    setActiveId(id);
    try { localStorage.setItem(SESSION_KEY, id); } catch { /* private mode: fine */ }
    setMessages([]);
    apiFetch(`/api/rag/sessions/${encodeURIComponent(id)}/messages`)
      .then(r => (r.ok ? r.json() : { messages: [] }))
      .then(d => setMessages(d.messages || []))
      .catch(() => {});
  }

  // "New chat": drop to a draft. No server row yet — handleQuery creates it lazily so
  // clicking New-chat-then-wandering-off doesn't leave empty sessions around.
  function newSession() {
    setActiveId(null);
    try { localStorage.removeItem(SESSION_KEY); } catch { /* ignore */ }
    setMessages([]);
  }

  // Two-step delete per sidebar row — a stray click shouldn't nuke months of research.
  async function handleDeleteSession(id) {
    if (confirmDeleteId !== id) { setConfirmDeleteId(id); setTimeout(() => setConfirmDeleteId(null), 4000); return; }
    try {
      const r = await apiFetch(`/api/rag/sessions/${encodeURIComponent(id)}`, { method: 'DELETE' });
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      if (id === activeId) newSession();
      refreshSessions();
    } catch (err) {
      console.error('Delete session failed:', err);
    } finally {
      setConfirmDeleteId(null);
    }
  }

  return (
    <div style={{ display: 'flex', gap: '12px', height: '100%' }}>
      {/* Session sidebar */}
      <aside style={{ width: '230px', flexShrink: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
        <button
          onClick={newSession}
          style={{
            padding: '8px 12px', fontSize: '13px', borderRadius: '6px', cursor: 'pointer',
            border: 'none', background: '#4a90d9', color: 'white', fontWeight: 600,
          }}
        >
          ＋ New chat
        </button>
        <div style={{ flex: 1, overflowY: 'auto' }}>
          {sessions.length === 0 && (
            <p style={{ fontSize: '12px', color: '#a0aec0', padding: '8px 4px' }}>No saved chats yet.</p>
          )}
          {sessions.map(s => (
            <div
              key={s.id}
              onClick={() => openSession(s.id)}
              style={{
                padding: '8px 10px', marginBottom: '4px', borderRadius: '6px', cursor: 'pointer',
                background: s.id === activeId ? '#e3f2fd' : 'transparent',
                border: `1px solid ${s.id === activeId ? '#90cdf4' : 'transparent'}`,
                display: 'flex', alignItems: 'center', gap: '6px',
              }}
            >
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: '13px', color: '#2d3748', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                  {s.title}
                </div>
                <div style={{ fontSize: '11px', color: '#a0aec0' }}>{new Date(s.updated_at + 'Z').toLocaleDateString()}</div>
              </div>
              <button
                onClick={(e) => { e.stopPropagation(); handleDeleteSession(s.id); }}
                title={confirmDeleteId === s.id ? 'Click again to confirm delete' : 'Delete chat'}
                style={{ border: 'none', background: 'none', cursor: 'pointer', fontSize: '12px', color: confirmDeleteId === s.id ? '#c53030' : '#a0aec0' }}
              >
                {confirmDeleteId === s.id ? '❌?' : '🗑'}
              </button>
            </div>
          ))}
        </div>
      </aside>

    <div style={{ flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: '16px' }}>
      <style>{MD_CSS}</style>
      {/* Status Bar */}
      {status && (
        <div style={{ 
          padding: '12px 16px', 
          background: '#f8f9fa', 
          borderRadius: '8px',
          fontSize: '13px',
          color: '#4a5568'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span>
              📚 {status.indexed_count || 0} of {status.total_docs || 0} documents indexed ({status.chunk_count || 0} chunks)
            </span>
            <button 
              onClick={handleIndex}
              disabled={loading || status.indexing}
              style={{
                padding: '6px 12px',
                fontSize: '13px',
                background: '#4a90d9',
                color: 'white',
                border: 'none',
                borderRadius: '6px',
                cursor: status.indexing ? 'not-allowed' : 'pointer',
                opacity: status.indexing ? 0.7 : 1
              }}
            >
              {status.indexing ? 'Indexing...' : '🔄 Re-index All'}
            </button>
          </div>
        </div>
      )}

      {/* Chat Messages */}
      <div style={{ 
        flex: 1, 
        overflowY: 'auto', 
        padding: '16px',
        background: '#fafbfc',
        borderRadius: '8px',
        border: '1px solid #e2e8f0'
      }}>
        {messages.length === 0 ? (
          <div style={{ textAlign: 'center', color: '#a0aec0', padding: '40px' }}>
            <p style={{ fontSize: '16px', marginBottom: '8px' }}>🔍 Ask a question about your documents</p>
            <p style={{ fontSize: '13px' }}>Try: "What is RAG?" or "Summarize the test report"</p>
          </div>
        ) : (
          messages.map((msg, i) => (
            <div key={msg.id ?? `local-${i}`} title={msg.created_at || undefined} style={{ 
              marginBottom: '16px',
              padding: '12px 16px',
              background: msg.role === 'user' ? '#e3f2fd' : '#fff',
              borderRadius: '8px',
              border: `1px solid ${msg.error ? '#fecaca' : '#e2e8f0'}`,
              maxWidth: '90%'
            }}>
              <div style={{ 
                fontSize: '11px', 
                fontWeight: 600, 
                color: msg.role === 'user' ? '#1565c0' : '#4a5568',
                marginBottom: '4px'
              }}>
                {msg.role === 'user' ? '👤 You' : '📖 Assistant'}
                {msg.model && (
                  <span style={{ fontWeight: 400, color: '#a0aec0', marginLeft: 8 }}>
                    · {msg.model}
                  </span>
                )}
              </div>
              <div style={{ 
                fontSize: '14px', 
                lineHeight: '1.5',
                ...(msg.role === 'assistant' && !msg.error ? {} : { whiteSpace: 'pre-wrap' }),
                color: msg.error ? '#c53030' : '#2d3748'
              }}>
                {msg.role === 'assistant' && !msg.error
                  ? <MarkdownAnswer content={msg.content} />
                  : msg.content}
              </div>
              {msg.llm_offline && (
                <div style={{ marginTop: '8px', fontSize: '12px', color: '#b7791f' }}>
                  ⚠ LLM unavailable — showing retrieved excerpts instead
                </div>
              )}
              
              {/* Sources */}
              {msg.sources && msg.sources.length > 0 && (
                <div style={{ marginTop: '12px', paddingTop: '8px', borderTop: '1px solid #e2e8f0' }}>
                  <div style={{ fontSize: '11px', fontWeight: 600, color: '#718096', marginBottom: '4px' }}>
                    Sources ({msg.sources.length}):
                  </div>
                  {msg.sources.map((src, j) => (
                    <div key={j} style={{ 
                      fontSize: '12px', 
                      color: '#4a5568',
                      padding: '4px 0'
                    }}>
                      📄 {src.title || src.filename} (chunk {src.chunk_index + 1}/{src.total_chunks})
                      {src.page_number && ` • page ${src.page_number}`}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))
        )}
        
        {/* Loading indicator */}
        {loading && (
          <div style={{ 
            padding: '12px 16px',
            background: '#fff',
            borderRadius: '8px',
            border: '1px solid #e2e8f0'
          }}>
            <span style={{ fontSize: '13px', color: '#a0aec0' }}>Thinking...</span>
          </div>
        )}
        
        {/* Scroll anchor */}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Form */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
          <button
            type="button"
            onClick={() => setSettingsOpen(o => !o)}
            title="Generation settings"
            style={{
              padding: '6px 10px', fontSize: '14px', border: '1px solid #e2e8f0',
              borderRadius: '6px', background: settingsOpen ? '#edf2f7' : '#fff', cursor: 'pointer'
            }}
          >
            ⚙
          </button>
        {models.length > 0 && (
          <>
            <label htmlFor="rag-model" style={{ fontSize: '12px', color: '#718096', whiteSpace: 'nowrap' }}>
              Model
            </label>
            <select
              id="rag-model"
              value={model}
              onChange={(e) => { const id = e.target.value; setModel(id); warmModel(id); }}
              disabled={loading}
              style={{
                flex: 1,
                maxWidth: '420px',
                padding: '6px 10px',
                fontSize: '13px',
                border: '1px solid #e2e8f0',
                borderRadius: '6px',
                background: '#fff',
                color: '#2d3748'
              }}
            >
              <option value="">Default (whatever LM Studio has loaded)</option>
              {models.map(m => (
                <option key={m.id} value={m.id}>
                  {m.state === 'loaded' ? `\u25CF ${m.id}`
                    : m.state === 'loading' ? `${m.id} (loading...)`
                    : `${m.id} \u2014 not loaded, first query pays the load`}
                </option>
              ))}
            </select>
          </>
        )}
        </div>
        {settingsOpen && <RagSettings settings={settings} onChange={updateSettings} />}
        <form onSubmit={handleQuery} style={{ display: 'flex', gap: '8px' }}>
        <input 
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask about your documents..."
          disabled={loading}
          style={{ 
            flex: 1,
            padding: '12px 16px',
            fontSize: '14px',
            border: '1px solid #e2e8f0',
            borderRadius: '8px',
            outline: 'none'
          }}
        />
        <button 
          type="submit"
          disabled={loading || !input.trim()}
          style={{
            padding: '12px 24px',
            fontSize: '14px',
            fontWeight: 600,
            background: '#4a90d9',
            color: 'white',
            border: 'none',
            borderRadius: '8px',
            cursor: loading || !input.trim() ? 'not-allowed' : 'pointer',
            opacity: loading || !input.trim() ? 0.5 : 1
          }}
        >
          Send
        </button>
        </form>
      </div>
    </div>
    </div>
  );
}
