/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L   14-161  =
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

import React, { useState, useEffect, useRef } from 'react';

/* ============================================================
   LUNAR LANDER — a space-race simulation, est. 1962
   Canvas game with touch + keyboard controls.
   World coordinates: fixed design space W x H (420 x 560),
   scaled to fit the container without distortion.
   ============================================================ */

const W = 420;
const H = 560;

// ---- physics tuning (design units / second) -----------------
const GRAVITY = 150;        // lunar pull, u/s^2
const THRUST_ACCEL = 300;   // engine acceleration along nose axis
const ROT_RATE = 2.4;       // rad/s
const FUEL_BURN = 20;       // units / second while thrusting
const MAX_VX = 260;

// landing tolerances (u/s)
const SOFT_VY = 45, SOFT_VX = 30, SOFT_ANGLE = 0.30;
const ROUGH_VY = 85, ROUGH_VX = 55, ROUGH_ANGLE = 0.42;

// ---- palette (atomic-age console) ----------------------------
const C = {
  skyTop: '#101a36',
  skyBot: '#1d2c55',
  star: '#f7f0dc',
  terrain: '#b96a2c',
  terrainEdge: '#8a4a1c',
  pad: '#2aa198',
  padStripe: '#e8dcc0',
  beacon: '#ff5a1f',
  shipBody: '#efe7d2',
  shipDark: '#c9bfa4',
  shipAccent: '#ff5a1f',
  window: '#7fd4c8',
  flameCore: '#ffd27a',
  flameOuter: '#ff7a2e',
  hudBg: 'rgba(13, 20, 42, 0.92)',
  hudText: '#ffb347',
  hudDim: '#8fa3d8',
};

// ---- helpers --------------------------------------------------
function rand(a, b) { return a + Math.random() * (b - a); }
function clamp(v, a, b) { return v < a ? a : v > b ? b : v; }

/* ---------------- terrain generation ---------------- */
function makeTerrain(level) {
  const padLen = Math.max(120 - level * 8, 64);
  const padStart = rand(padLen / 2 + 30, W - padLen / 2 - 30);
  const padEnd = padStart + padLen;

  const step = 21;
  const pts = [];
  let y = rand(H * 0.62, H * 0.80);
  for (let x = 0; x <= W + step; x += step) {
    if (x >= padStart - step && x <= padEnd + step) {
      // flatten the landing zone at a fixed height
      y = clamp((padStart + padEnd) / 2 > x ? y : y, H * 0.58, H * 0.9);
    } else {
      y += rand(-46, 46);
      // keep away from the pad height so cliffs read clearly
      if (x < padStart - step || x > padEnd + step) {
        const padY = clamp(H * 0.72, H * 0.58, H * 0.9);
        y += (padY - y) * 0.15;
      }
    }
    y = clamp(y, H * 0.55, H * 0.93);
    pts.push({ x, y });
  }

  // force the pad segment perfectly flat at a chosen height
  const padY = clamp(H * rand(0.62, 0.84), H * 0.58, H * 0.9);
  for (const p of pts) {
    if (p.x >= padStart - step && p.x <= padEnd + step) p.y = padY;
  }

  return { pts, padStart, padEnd, padY };
}

function groundHeight(terrain, x) {
  const { pts } = terrain;
  if (x <= pts[0].x) return pts[0].y;
  for (let i = 1; i < pts.length; i++) {
    if (x <= pts[i].x) {
      const a = pts[i - 1], b = pts[i];
      const t = (x - a.x) / (b.x - a.x);
      return a.y + (b.y - a.y) * t;
    }
  }
  return pts[pts.length - 1].y;
}

/* ---------------- tiny WebAudio synth ---------------- */
function makeAudio() {
  let ctx = null, thrGain = null, thrSrc = null;
  function ensure() {
    if (!ctx) {
      try { ctx = new (window.AudioContext || window.webkitAudioContext)(); } catch (e) { return null; }
    }
    if (ctx && ctx.state === 'suspended') ctx.resume();
    return ctx;
  }
  function thrust(on) {
    const c = ensure(); if (!c) return;
    if (on && !thrSrc) {
      const len = c.sampleRate * 1.2;
      const buf = c.createBuffer(1, len, c.sampleRate);
      const d = buf.getChannelData(0);
      for (let i = 0; i < len; i++) d[i] = Math.random() * 2 - 1;
      thrSrc = c.createBufferSource(); thrSrc.buffer = buf; thrSrc.loop = true;
      const filt = c.createBiquadFilter(); filt.type = 'bandpass'; filt.frequency.value = 420; filt.Q.value = 0.8;
      thrGain = c.createGain(); thrGain.gain.value = 0.0;
      thrSrc.connect(filt); filt.connect(thrGain); thrGain.connect(c.destination);
      thrSrc.start();
      thrGain.gain.linearRampToValueAtTime(0.16, c.currentTime + 0.08);
    } else if (!on && thrSrc) {
      const s = thrSrc;
      try { thrGain.gain.linearRampToValueAtTime(0.0, c.currentTime + 0.12); } catch (e) {}
      setTimeout(() => { try { s.stop(); } catch (e) {} }, 160);
      thrSrc = null; thrGain = null;
    }
  }
  function tone(freq, dur, type, vol, when) {
    const c = ensure(); if (!c) return;
    const t0 = c.currentTime + (when || 0);
    const o = c.createOscillator(), g = c.createGain();
    o.type = type || 'square'; o.frequency.value = freq;
    g.gain.setValueAtTime(vol || 0.12, t0);
    g.gain.exponentialRampToValueAtTime(0.001, t0 + dur);
    o.connect(g); g.connect(c.destination);
    o.start(t0); o.stop(t0 + dur + 0.05);
  }
  function chime() { tone(660, 0.12, 'square', 0.14); tone(880, 0.2, 'square', 0.14, 0.13); tone(1320, 0.35, 'triangle', 0.12, 0.26); }
  function boom() {
    const c = ensure(); if (!c) return;
    const len = c.sampleRate * 0.7;
    const buf = c.createBuffer(1, len, c.sampleRate);
    const d = buf.getChannelData(0);
    for (let i = 0; i < len; i++) d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, 2);
    const s = c.createBufferSource(); s.buffer = buf;
    const g = c.createGain(); g.gain.value = 0.35;
    s.connect(g); g.connect(c.destination); s.start();
    tone(160, 0.4, 'sawtooth', 0.2); tone(90, 0.6, 'triangle', 0.22, 0.08);
  }
  return { thrust, chime, boom };
}

/* ============================================================ */
export default function LunarLander() {
  const canvasRef = useRef(null);
  const [phase, setPhase] = useState('title'); // title | playing | landed | crashed
  const [stats, setStats] = useState({ score: 0, best: 0, level: 1, fuel: 0 });

  const phaseRef = useRef(phase);
  phaseRef.current = phase;
  const inputRef = useRef({ left: false, right: false, thrust: false });
  const apiRef = useRef({});

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx2d = canvas.getContext('2d');
    const audio = makeAudio();

    // ---- world state (mutable, lives outside React) ----------
    let terrain = null;
    let ship = null;
    let particles = [];
    let stars = [];
    let score = 0, level = 1, fuelLeft = 0;
    let endTimer = 0; // ms until overlay shown after crash/landing
    let best = 0;
    try { best = parseInt(localStorage.getItem('lunarLanderBest') || '0', 10) || 0; } catch (e) {}

    for (let i = 0; i < 80; i++) stars.push({ x: rand(0, W), y: rand(50, H * 0.7), r: rand(0.4, 1.6), ph: rand(0, 6.28) });

    function startLevel(lv) {
      level = lv;
      terrain = makeTerrain(level);
      fuelLeft = Math.max(55, 100 - (level - 1) * 6);
      ship = {
        x: rand(W * 0.3, W * 0.7), y: 90,
        vx: rand(-32, 32), vy: 0,
        angle: 0, thrusting: false, dead: false, landed: false,
      };
      particles = [];
      endTimer = 0;
    }

    function explode(x, y) {
      for (let i = 0; i < 46; i++) {
        const a = rand(0, Math.PI * 2), sp = rand(30, 240);
        particles.push({ x, y, vx: Math.cos(a) * sp, vy: Math.sin(a) * sp - 40, life: rand(0.5, 1.2), t: 0, r: rand(1.5, 4.5), c: i % 3 === 0 ? C.flameCore : (i % 3 === 1 ? C.beacon : '#efe7d2') });
      }
    }

    function update(dt) {
      if (!ship || phaseRef.current !== 'playing') return;

      // particles always integrate (even during the end-of-event pause)
      for (const p of particles) { p.t += dt; p.x += p.vx * dt; p.y += p.vy * dt; p.vy += 60 * dt; }
      particles = particles.filter(p => p.t < p.life);

      // end-of-event timer -> flip React phase for overlay
      if (endTimer > 0) {
        endTimer -= dt * 1000;
        if (endTimer <= 0 && ship) {
          setStats({ score, best, level, fuel: Math.round(fuelLeft) });
          setPhase(ship.dead ? 'crashed' : 'landed');
        }
      }

      // once the outcome is decided, freeze the sim until the overlay shows
      if (ship.dead || ship.landed) return;

      const inp = inputRef.current;

      // rotation
      if (inp.left) ship.angle -= ROT_RATE * dt;
      if (inp.right) ship.angle += ROT_RATE * dt;
      ship.angle = clamp(ship.angle, -1.35, 1.35);

      // thrust along nose axis
      const wantThrust = inp.thrust && fuelLeft > 0;
      ship.thrusting = wantThrust;
      if (wantThrust) {
        ship.vx += Math.sin(ship.angle) * THRUST_ACCEL * dt;
        ship.vy -= Math.cos(ship.angle) * THRUST_ACCEL * dt;
        fuelLeft = Math.max(0, fuelLeft - FUEL_BURN * dt);
      }
      audio.thrust(wantThrust && phaseRef.current === 'playing');

      // gravity + integrate
      ship.vy += GRAVITY * dt;
      ship.vx = clamp(ship.vx, -MAX_VX, MAX_VX);
      ship.x += ship.vx * dt;
      ship.y += ship.vy * dt;

      // walls: bounce softly off left/right
      if (ship.x < 14) { ship.x = 14; ship.vx *= -0.35; }
      if (ship.x > W - 14) { ship.x = W - 14; ship.vx *= -0.35; }

      // terrain collision — sample under the hull and both legs
      const legDrop = 16;
      const gx = ship.x, gy = groundHeight(terrain, gx);
      const bottomY = ship.y + legDrop * Math.cos(ship.angle);
      if (bottomY >= gy) {
        // local slope under the ship
        const sL = groundHeight(terrain, gx - 12), sR = groundHeight(terrain, gx + 12);
        const slopeAngle = Math.atan2(sR - sL, 24);
        let rel = ship.angle - slopeAngle;
        while (rel > Math.PI) rel -= 2 * Math.PI;
        while (rel < -Math.PI) rel += 2 * Math.PI;

        const onPad = gx >= terrain.padStart && gx <= terrain.padEnd;
        const soft = Math.abs(ship.vy) <= SOFT_VY && Math.abs(ship.vx) <= SOFT_VX && Math.abs(rel) <= SOFT_ANGLE;
        const rough = Math.abs(ship.vy) <= ROUGH_VY && Math.abs(ship.vx) <= ROUGH_VX && Math.abs(rel) <= ROUGH_ANGLE;

        if (onPad ? rough : (Math.abs(ship.vy) <= 30 && Math.abs(ship.vx) <= 14 && Math.abs(slopeAngle) <= 0.18)) {
          // ---- successful touchdown ----
          ship.landed = true;
          ship.y = gy - legDrop * Math.cos(ship.angle);
          ship.vy = 0; ship.vx = 0;
          const bonus = soft ? 300 : (onPad ? 120 : 60);
          score += 500 + Math.round(fuelLeft * 8) + bonus;
          if (score > best) { best = score; try { localStorage.setItem('lunarLanderBest', String(best)); } catch (e) {} }
          audio.thrust(false); audio.chime();
          for (let i = 0; i < 14; i++) particles.push({ x: ship.x + rand(-16, 16), y: gy - 2, vx: rand(-50, 50), vy: rand(-70, -10), life: rand(0.4, 0.9), t: 0, r: rand(1.5, 3.5), c: '#d8c9a3' });
          endTimer = 900;
        } else {
          // ---- crash ----
          ship.dead = true;
          explode(ship.x, Math.min(ship.y + 10, gy - 6));
          audio.thrust(false); audio.boom();
          if (score > best) { best = score; try { localStorage.setItem('lunarLanderBest', String(best)); } catch (e) {} }
          endTimer = 1100;
        }
      }
    }

    // ---------------- rendering ------------------------------
    function drawShip() {
      ctx2d.save();
      ctx2d.translate(ship.x, ship.y);
      ctx2d.rotate(ship.angle);
      if (ship.dead) { ctx2d.globalAlpha = 0.9; }

      // thruster flame
      if (ship.thrusting && !ship.dead) {
        const f = rand(14, 26);
        ctx2d.beginPath();
        ctx2d.moveTo(-5, 13);
        ctx2d.lineTo(0, 13 + f);
        ctx2d.lineTo(5, 13);
        ctx2d.closePath();
        ctx2d.fillStyle = C.flameOuter; ctx2d.fill();
        ctx2d.beginPath();
        ctx2d.moveTo(-2.5, 13);
        ctx2d.lineTo(0, 13 + f * 0.6);
        ctx2d.lineTo(2.5, 13);
        ctx2d.closePath();
        ctx2d.fillStyle = C.flameCore; ctx2d.fill();
      }

      // legs
      ctx2d.strokeStyle = C.shipDark; ctx2d.lineWidth = 2.4;
      ctx2d.beginPath();
      ctx2d.moveTo(-6, 8); ctx2d.lineTo(-13, 17);
      ctx2d.moveTo(6, 8); ctx2d.lineTo(13, 17);
      ctx2d.stroke();
      ctx2d.lineWidth = 2;
      ctx2d.beginPath();
      ctx2d.moveTo(-16, 17); ctx2d.lineTo(-10, 17);
      ctx2d.moveTo(10, 17); ctx2d.lineTo(16, 17);
      ctx2d.stroke();

      // body (capsule)
      ctx2d.beginPath();
      ctx2d.moveTo(0, -18);
      ctx2d.bezierCurveTo(9, -14, 9, 4, 7, 10);
      ctx2d.lineTo(-7, 10);
      ctx2d.bezierCurveTo(-9, 4, -9, -14, 0, -18);
      ctx2d.closePath();
      const grad = ctx2d.createLinearGradient(-9, 0, 9, 0);
      grad.addColorStop(0, C.shipDark);
      grad.addColorStop(0.5, C.shipBody);
      grad.addColorStop(1, C.shipDark);
      ctx2d.fillStyle = grad; ctx2d.fill();
      ctx2d.strokeStyle = '#6b6350'; ctx2d.lineWidth = 1; ctx2d.stroke();

      // nose accent band + porthole (chrome '62 style)
      ctx2d.beginPath();
      ctx2d.arc(0, -4, 4.6, 0, Math.PI * 2);
      ctx2d.fillStyle = C.window; ctx2d.fill();
      ctx2d.strokeStyle = '#3c5a5e'; ctx2d.lineWidth = 1.4; ctx2d.stroke();
      ctx2d.beginPath();
      ctx2d.moveTo(-7, 6); ctx2d.lineTo(7, 6);
      ctx2d.strokeStyle = C.shipAccent; ctx2d.lineWidth = 2; ctx2d.stroke();

      // antenna
      ctx2d.beginPath(); ctx2d.moveTo(0, -18); ctx2d.lineTo(0, -24);
      ctx2d.strokeStyle = '#6b6350'; ctx2d.lineWidth = 1.2; ctx2d.stroke();
      ctx2d.fillStyle = C.beacon;
      ctx2d.beginPath(); ctx2d.arc(0, -25, 1.6, 0, Math.PI * 2); ctx2d.fill();

      ctx2d.restore();
    }

    function drawTerrain() {
      const { pts, padStart, padEnd, padY } = terrain;
      // ground fill
      ctx2d.beginPath();
      ctx2d.moveTo(0, H);
      for (const p of pts) ctx2d.lineTo(p.x, p.y);
      ctx2d.lineTo(W, H);
      ctx2d.closePath();
      const g = ctx2d.createLinearGradient(0, H * 0.5, 0, H);
      g.addColorStop(0, C.terrain);
      g.addColorStop(1, '#7c431a');
      ctx2d.fillStyle = g; ctx2d.fill();

      // surface line + hatch marks (retro technical drawing)
      ctx2d.beginPath();
      for (let i = 0; i < pts.length; i++) { const p = pts[i]; if (i === 0) ctx2d.moveTo(p.x, p.y); else ctx2d.lineTo(p.x, p.y); }
      ctx2d.strokeStyle = C.terrainEdge; ctx2d.lineWidth = 2; ctx2d.stroke();

      ctx2d.save();
      ctx2d.beginPath();
      for (let i = 0; i < pts.length; i++) { const p = pts[i]; if (i === 0) ctx2d.moveTo(p.x, p.y); else ctx2d.lineTo(p.x, p.y); }
      ctx2d.lineTo(W, H); ctx2d.lineTo(0, H); ctx2d.closePath();
      ctx2d.clip();
      ctx2d.strokeStyle = 'rgba(60, 30, 8, 0.35)'; ctx2d.lineWidth = 1;
      for (let x = -H; x < W + H; x += 14) {
        ctx2d.beginPath(); ctx2d.moveTo(x, H * 0.5); ctx2d.lineTo(x + H * 0.5, H); ctx2d.stroke();
      }
      ctx2d.restore();

      // landing pad: striped platform + beacon
      const py = groundHeight(terrain, (padStart + padEnd) / 2);
      ctx2d.fillStyle = C.pad;
      ctx2d.fillRect(padStart - 4, py - 5, padEnd - padStart + 8, 6);
      for (let x = padStart; x < padEnd; x += 16) {
        ctx2d.fillStyle = C.padStripe;
        ctx2d.fillRect(x, py - 5, 8, 6);
      }
      // beacon light on the near edge
      const blink = (Math.sin(performance.now() / 180) + 1) / 2;
      ctx2d.fillStyle = `rgba(255, 90, 31, ${0.35 + 0.65 * blink})`;
      ctx2d.beginPath(); ctx2d.arc(padEnd + 4, py - 8, 3.2, 0, Math.PI * 2); ctx2d.fill();
    }

    function drawHUD() {
      const t = performance.now();
      // top console strip
      ctx2d.fillStyle = C.hudBg;
      ctx2d.fillRect(0, 0, W, 46);
      ctx2d.strokeStyle = 'rgba(255,179,71,0.35)';
      ctx2d.lineWidth = 1;
      ctx2d.beginPath(); ctx2d.moveTo(0, 46.5); ctx2d.lineTo(W, 46.5); ctx2d.stroke();

      ctx2d.font = 'bold 11px "Courier New", monospace';
      ctx2d.textBaseline = 'alphabetic';

      // fuel gauge
      ctx2d.fillStyle = C.hudDim;
      ctx2d.fillText('FUEL', 14, 18);
      const fw = 90, fh = 10, fx = 14, fy = 24;
      ctx2d.strokeStyle = C.hudText; ctx2d.lineWidth = 1;
      ctx2d.strokeRect(fx, fy, fw, fh);
      const frac = fuelLeft / Math.max(55, 100 - (level - 1) * 6);
      ctx2d.fillStyle = frac > 0.3 ? C.beacon : '#ff3b30';
      if (frac < 0.25 && Math.sin(t / 120) > 0) ctx2d.fillStyle = '#ffd27a';
      ctx2d.fillRect(fx + 1, fy + 1, (fw - 2) * clamp(frac, 0, 1), fh - 2);

      // velocity + altitude readouts
      const spd = ship ? Math.round(Math.hypot(ship.vx, ship.vy)) : 0;
      const alt = ship && terrain ? Math.max(0, Math.round(groundHeight(terrain, ship.x) - ship.y - 16)) : 0;
      ctx2d.fillStyle = C.hudText;
      ctx2d.fillText('VEL ' + String(spd).padStart(3, ' ') + ' m/s', 140, 18);
      ctx2d.fillText('ALT ' + String(alt).padStart(3, ' ') + ' m', 140, 36);

      // level + score on the right
      ctx2d.textAlign = 'right';
      ctx2d.fillStyle = C.hudText;
      ctx2d.fillText('MISSION ' + String(level).padStart(2, '0'), W - 14, 18);
      ctx2d.fillText('SCORE ' + score, W - 14, 36);
      ctx2d.textAlign = 'left';

      // status lamp
      const lamp = phaseRef.current === 'playing' ? (ship && ship.thrusting ? '#7dff9a' : '#ffb347') : '#ff5a1f';
      ctx2d.fillStyle = lamp;
      ctx2d.beginPath(); ctx2d.arc(W - 8, 8, 0, 0, Math.PI * 2); // placeholder (drawn below)
      ctx2d.fill();
    }

    function draw(t) {
      const dpr = window.devicePixelRatio || 1;
      const cw = canvas.width / dpr, chh = canvas.height / dpr;
      const sx = cw / W, sy = chh / H;
      ctx2d.setTransform(dpr * sx, 0, 0, dpr * sy, 0, 0);

      // sky gradient
      const g = ctx2d.createLinearGradient(0, 0, 0, H);
      g.addColorStop(0, C.skyTop);
      g.addColorStop(1, C.skyBot);
      ctx2d.fillStyle = g;
      ctx2d.fillRect(-2, -2, W + 4, H + 4);

      // stars (twinkle)
      for (const s of stars) {
        const a = 0.35 + 0.65 * Math.abs(Math.sin(t / 900 + s.ph));
        ctx2d.globalAlpha = a;
        ctx2d.fillStyle = C.star;
        ctx2d.fillRect(s.x, s.y, s.r, s.r);
      }
      ctx2d.globalAlpha = 1;

      // Earth, small and far (we are on the Moon after all)
      const ex = W - 64, ey = 96, er = 30;
      ctx2d.save();
      ctx2d.beginPath(); ctx2d.arc(ex, ey, er, 0, Math.PI * 2); ctx2d.clip();
      const eg = ctx2d.createRadialGradient(ex - 10, ey - 10, 4, ex, ey, er + 6);
      eg.addColorStop(0, '#9fd8cf');
      eg.addColorStop(0.55, '#3f7fae');
      eg.addColorStop(1, '#274b7a');
      ctx2d.fillStyle = eg;
      ctx2d.fillRect(ex - er, ey - er, er * 2, er * 2);
      // cloud bands
      ctx2d.globalAlpha = 0.5;
      ctx2d.strokeStyle = '#e8f4ef'; ctx2d.lineWidth = 3;
      for (let i = -2; i <= 2; i++) {
        ctx2d.beginPath();
        ctx2d.arc(ex + i * 9, ey + 14, er * 0.75, Math.PI * 1.05, Math.PI * 1.6);
        ctx2d.stroke();
      }
      // terminator shadow
      ctx2d.globalAlpha = 1;
      const tg = ctx2d.createLinearGradient(ex - er, ey, ex + er, ey);
      tg.addColorStop(0.55, 'rgba(8,14,34,0)');
      tg.addColorStop(1, 'rgba(8,14,34,0.92)');
      ctx2d.fillStyle = tg;
      ctx2d.fillRect(ex - er, ey - er, er * 2, er * 2);
      ctx2d.restore();

      if (terrain) drawTerrain();
      if (ship && !ship.dead) drawShip();

      // particles
      for (const p of particles) {
        ctx2d.globalAlpha = clamp(1 - p.t / p.life, 0, 1);
        ctx2d.fillStyle = p.c;
        ctx2d.beginPath(); ctx2d.arc(p.x, p.y, p.r, 0, Math.PI * 2); ctx2d.fill();
      }
      ctx2d.globalAlpha = 1;

      if (terrain) drawHUD();
    }

    // ---------------- main loop --------------------------------
    let raf = 0, last = performance.now();
    function frame(now) {
      const dt = clamp((now - last) / 1000, 0, 0.05);
      last = now;
      update(dt);
      draw(now);
      raf = requestAnimationFrame(frame);
    }

    // ---------------- sizing -----------------------------------
    function resize() {
      const dpr = window.devicePixelRatio || 1;
      const rect = canvas.parentElement.getBoundingClientRect();
      const cssW = Math.max(280, rect.width);
      const cssH = cssW * (H / W);
      canvas.style.width = cssW + 'px';
      canvas.style.height = cssH + 'px';
      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
    }
    resize();
    window.addEventListener('resize', resize);

    // ---------------- keyboard ---------------------------------
    function setKey(e, down) {
      const k = e.key;
      if (k === 'ArrowLeft' || k === 'a') inputRef.current.left = down;
      else if (k === 'ArrowRight' || k === 'd') inputRef.current.right = down;
      else if (k === 'ArrowUp' || k === 'w' || k === ' ') { inputRef.current.thrust = down; e.preventDefault(); }
    }
    const kd = (e) => setKey(e, true);
    const ku = (e) => setKey(e, false);
    window.addEventListener('keydown', kd);
    window.addEventListener('keyup', ku);

    // ---------------- public API for overlay buttons -----------
    apiRef.current = {
      launch() { score = 0; startLevel(1); inputRef.current = { left: false, right: false, thrust: false }; setPhase('playing'); },
      next() { startLevel(level + 1); inputRef.current = { left: false, right: false, thrust: false }; setPhase('playing'); },
      retry() { score = Math.max(0, score - 250); if (score < 0) score = 0; startLevel(level); inputRef.current = { left: false, right: false, thrust: false }; setPhase('playing'); },
      menu() { audio.thrust(false); terrain = null; ship = null; particles = []; setStats({ score, best, level, fuel: 0 }); setPhase('title'); },
    };

    raf = requestAnimationFrame(frame);
    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener('resize', resize);
      window.removeEventListener('keydown', kd);
      window.removeEventListener('keyup', ku);
      audio.thrust(false);
    };
  }, []);

  // ---- touch control helpers ----------------------------------
  function hold(key) {
    return {
      onPointerDown: (e) => { e.preventDefault(); inputRef.current[key] = true; },
      onPointerUp: () => { inputRef.current[key] = false; },
      onPointerLeave: () => { inputRef.current[key] = false; },
      onPointerCancel: () => { inputRef.current[key] = false; },
    };
  }

  const keyBtnStyle = {
    flex: 1,
    minHeight: '64px',
    border: '2px solid #1a2340',
    borderRadius: '10px',
    background: '#f4ead8',
    color: '#1a2340',
    fontSize: '22px',
    fontWeight: 700,
    fontFamily: '"Courier New", monospace',
    boxShadow: '0 5px 0 #1a2340',
    touchAction: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    cursor: 'pointer',
    padding: 0,
  };

  return (
    <div style={{ maxWidth: '520px', margin: '16px auto', textAlign: 'center' }}>
      {/* console frame */}
      <div style={{
        border: '3px solid #1a2340', borderRadius: '14px', background: '#f4ead8',
        boxShadow: '0 8px 0 rgba(26,35,64,0.25)', padding: '10px', position: 'relative', overflow: 'hidden',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '2px 6px 8px' }}>
          <span style={{ fontFamily: '"Courier New", monospace', fontWeight: 700, color: '#1a2340', fontSize: '13px', letterSpacing: '1px' }}>
            ★ LUNAR LANDER · SPACE RACE DIV.
          </span>
          <span style={{ fontFamily: '"Courier New", monospace', color: '#8a7f66', fontSize: '12px' }}>EST. 1962</span>
        </div>

        {/* canvas + scanlines */}
        <div style={{ position: 'relative', margin: '0 auto', maxWidth: '460px' }} onContextMenu={(e) => e.preventDefault()}>
          <canvas ref={canvasRef} style={{ display: 'block', width: '100%', borderRadius: '8px', background: C.skyTop }} />
          <div style={{
            position: 'absolute', inset: 0, pointerEvents: 'none', borderRadius: '8px',
            background: 'repeating-linear-gradient(0deg, rgba(255,255,255,0.03) 0px, rgba(255,255,255,0.03) 1px, transparent 1px, transparent 3px)',
            boxShadow: 'inset 0 0 60px rgba(8,14,34,0.55)',
          }} />

          {/* ---------- overlays ---------- */}
          {phase !== 'playing' && (
            <div style={{
              position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column',
              alignItems: 'center', justifyContent: 'center', gap: '14px',
              background: phase === 'title' ? 'rgba(13,20,42,0.55)' : 'rgba(13,20,42,0.78)',
              borderRadius: '8px', padding: '20px',
            }}>
              {phase === 'title' && (
                <>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#f4ead8', fontSize: '34px', fontWeight: 700, letterSpacing: '4px', textShadow: '0 3px 0 rgba(255,90,31,0.6)' }}>
                    LUNAR<br />LANDER
                  </div>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#ffb347', fontSize: '12px', letterSpacing: '2px' }}>
                    A SPACE RACE SIMULATION · EST. 1962
                  </div>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#c8d4f5', fontSize: '12px', maxWidth: '300px', lineHeight: 1.7 }}>
                    Set down the lander on the striped pad with gentle velocity and a level attitude. Fuel is precious, Commander.
                  </div>
                  {stats.best > 0 && (
                    <div style={{ fontFamily: '"Courier New", monospace', color: '#7dff9a', fontSize: '13px' }}>
                      BEST SCORE — {stats.best}
                    </div>
                  )}
                </>
              )}

              {phase === 'landed' && (
                <>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#7dff9a', fontSize: '26px', fontWeight: 700, letterSpacing: '3px' }}>
                    LANDING CONFIRMED
                  </div>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#c8d4f5', fontSize: '13px', lineHeight: 2 }}>
                    MISSION {stats.level} COMPLETE<br />
                    FUEL RESERVE — {stats.fuel}<br />
                    TOTAL SCORE — <span style={{ color: '#ffb347' }}>{stats.score}</span>
                  </div>
                </>
              )}

              {phase === 'crashed' && (
                <>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#ff5a1f', fontSize: '26px', fontWeight: 700, letterSpacing: '3px' }}>
                    SIGNAL LOST
                  </div>
                  <div style={{ fontFamily: '"Courier New", monospace', color: '#c8d4f5', fontSize: '13px', lineHeight: 2 }}>
                    THE MISSION CONTROL IS SORRY.<br />
                    SCORE — {stats.score} · BEST — {stats.best}
                  </div>
                </>
              )}

              <button className="btn btn-primary" style={{ fontSize: '16px', padding: '12px 34px' }} onClick={() => apiRef.current[phase === 'title' ? 'launch' : phase === 'landed' ? 'next' : 'retry']()}>
                {phase === 'title' ? '▶ LAUNCH MISSION' : phase === 'landed' ? '▶ NEXT MISSION' : '↺ RETRY MISSION'}
              </button>
              {phase !== 'title' && (
                <button className="btn btn-ghost" style={{ fontSize: '13px' }} onClick={() => apiRef.current.menu()}>MAIN MENU</button>
              )}
            </div>
          )}
        </div>

        {/* ---------- control deck ---------- */}
        <div style={{ display: 'flex', gap: '10px', marginTop: '12px' }}>
          <button aria-label="Rotate left" {...hold('left')} style={keyBtnStyle}>⟲</button>
          <button
            aria-label="Thrust"
            {...hold('thrust')}
            style={{ ...keyBtnStyle, flex: 1.6, background: '#ff5a1f', color: '#fff8ec', fontSize: '17px', letterSpacing: '2px' }}
          >
            ▲ THRUST
          </button>
          <button aria-label="Rotate right" {...hold('right')} style={keyBtnStyle}>⟳</button>
        </div>

        <div style={{ fontFamily: '"Courier New", monospace', color: '#8a7f66', fontSize: '11px', marginTop: '10px' }}>
          TOUCH THE KEYS OR USE ← → ROTATE · ↑ / SPACE THRUST
        </div>
      </div>
    </div>
  );
}
