/**
 * ====================================================================
 * TABLE OF CONTENTS
 * ====================================================================
 *
 *  L  253-393  PROJECT MODAL COMPONENT
 *
 * (generated by scripts/gen_toc.py — do not hand-edit line numbers; rerun --write)
 * ====================================================================
 */

import React, { useState, useEffect } from 'react';
import { apiFetch } from '../api';

export default function ProjectHub() {
  const [projects, setProjects] = useState([]);
  const [stats, setStats] = useState(null);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingProject, setEditingProject] = useState(null);

  // Debounced search - wait 300ms after user stops typing
  const [debouncedSearch, setDebouncedSearch] = useState(search);
  useEffect(() => {
    const timer = setTimeout(() => setDebouncedSearch(search), 300);
    return () => clearTimeout(timer);
  }, [search]);

  // Reload projects when debounced search or filters change
  useEffect(() => {
    loadProjects();
  }, [debouncedSearch, statusFilter, priorityFilter]);

  // Load stats once on mount
  useEffect(() => {
    apiFetch('/api/stats')
      .then(r => r.json())
      .then(data => setStats(data))
      .catch(err => console.error('Failed to load stats:', err));
  }, []);

  async function loadProjects() {
    try {
      const params = new URLSearchParams();
      if (statusFilter) params.set('status', statusFilter);
      if (priorityFilter) params.set('priority', priorityFilter);
      if (debouncedSearch) params.set('search', debouncedSearch);

      let url = '/api/projects' + (params.toString() ? '?' + params : '');
      const res = await apiFetch(url);
      if (!res.ok) throw new Error(`API error ${res.status}`);
      const data = await res.json();
      setProjects(data);
    } catch (err) {
      console.error('Failed to load projects:', err);
    }
  }

  async function handleSaveProject(projectData) {
    try {
      if (editingProject) {
        const res = await apiFetch(`/api/projects/${editingProject.id}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(projectData),
        });
        if (!res.ok) throw new Error(`API error ${res.status}`);
        const updated = await res.json();
        setProjects(projects.map(p => p.id === updated.id ? updated : p));
      } else {
        const res = await apiFetch('/api/projects', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(projectData),
        });
        if (!res.ok) throw new Error(`API error ${res.status}`);
        const created = await res.json();
        setProjects([created, ...projects]);
      }
      setShowModal(false);
      setEditingProject(null);
      apiFetch('/api/stats')
        .then(r => r.json())
        .then(data => setStats(data))
        .catch(() => {});
    } catch (err) {
      console.error('Failed to save project:', err);
      alert('Failed to save project');
    }
  }

  async function handleDeleteProject(id) {
    if (!confirm('Are you sure you want to delete this project?')) return;
    try {
      const res = await apiFetch(`/api/projects/${id}`, { method: 'DELETE' });
      if (!res.ok) throw new Error(`API error ${res.status}`);
      setProjects(projects.filter(p => p.id !== id));
      apiFetch('/api/stats')
        .then(r => r.json())
        .then(data => setStats(data))
        .catch(() => {});
    } catch (err) {
      console.error('Failed to delete project:', err);
    }
  }

  function openNewProjectModal() {
    setEditingProject(null);
    setShowModal(true);
  }

  function openEditModal(project) {
    setEditingProject(project);
    setShowModal(true);
  }

  return (
    <div className="project-hub">
      {/* Stats Bar */}
      {stats && (
        <div className="stats-bar">
          <div className="stat-card">
            <div className="number">{stats.total}</div>
            <div className="label">Total</div>
          </div>
          <div className="stat-card">
            <div className="number" style={{ color: '#00b894' }}>{stats.completed}</div>
            <div className="label">Completed</div>
          </div>
          <div className="stat-card">
            <div className="number" style={{ color: '#3498db' }}>{stats.inProgress}</div>
            <div className="label">In Progress</div>
          </div>
          <div className="stat-card">
            <div className="number" style={{ color: '#e74c3c' }}>{stats.overdue}</div>
            <div className="label">Overdue</div>
          </div>
        </div>
      )}

      {/* Toolbar */}
      <div className="toolbar">
        <input
          type="text"
          className="search-box"
          placeholder="Search projects..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <select
          className="filter-select"
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
        >
          <option value="">All Statuses</option>
          <option value="not-started">Not Started</option>
          <option value="in-progress">In Progress</option>
          <option value="on-hold">On Hold</option>
          <option value="completed">Completed</option>
        </select>
        <select
          className="filter-select"
          value={priorityFilter}
          onChange={(e) => setPriorityFilter(e.target.value)}
        >
          <option value="">All Priorities</option>
          <option value="high">High</option>
          <option value="medium">Medium</option>
          <option value="low">Low</option>
        </select>
        <button className="btn btn-primary" onClick={openNewProjectModal}>
          + New Project
        </button>
      </div>

      {/* Projects Table */}
      {projects.length === 0 ? (
        <div className="empty-state">
          <div className="icon">📋</div>
          <p>No projects yet. Click "+ New Project" to get started!</p>
        </div>
      ) : (
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Priority</th>
                <th>Progress</th>
                <th>Deadline</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {projects.map(project => (
                <tr key={project.id}>
                  <td><strong>{project.name}</strong></td>
                  <td>
                    <span className={`badge badge-${project.status}`}>
                      {project.status.replace('-', ' ')}
                    </span>
                  </td>
                  <td>
                    <span className={`priority-${project.priority}`}>
                      {project.priority.charAt(0).toUpperCase() + project.priority.slice(1)}
                    </span>
                  </td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      <div className="progress-bar" style={{ width: '60px' }}>
                        <div
                          className="progress-fill"
                          style={{
                            width: `${project.progress}%`,
                            background: project.progress >= 100 ? '#00b894' : (project.progress > 50 ? '#3498db' : '#f39c12'),
                          }}
                        />
                      </div>
                      <span>{project.progress}%</span>
                    </div>
                  </td>
                  <td>{project.deadline || '—'}</td>
                  <td style={{ whiteSpace: 'nowrap' }}>
                    <button className="btn btn-sm btn-ghost" onClick={() => openEditModal(project)}>
                      Edit
                    </button>
                    <button className="btn btn-sm btn-danger" onClick={() => handleDeleteProject(project.id)}>
                      ×
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {/* Project Modal */}
      {showModal && (
        <ProjectModal
          project={editingProject}
          onSave={handleSaveProject}
          onClose={() => { setShowModal(false); setEditingProject(null); }}
        />
      )}
    </div>
  );
}

// ==================== PROJECT MODAL COMPONENT ====================
function ProjectModal({ project, onSave, onClose }) {
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    status: 'not-started',
    priority: 'medium',
    progress: 0,
    deadline: '',
    owner: '',
    tags: '',
    ...project,
  });

  function handleSubmit(e) {
    e.preventDefault();
    if (!formData.name.trim()) {
      alert('Project name is required');
      return;
    }
    onSave(formData);
  }

  return (
    <div className="modal-overlay active" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <h2>{project ? 'Edit Project' : 'New Project'}</h2>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="projName">Project Name *</label>
            <input
              type="text"
              id="projName"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="Enter project name..."
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="projDesc">Description</label>
            <textarea
              id="projDesc"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Brief description..."
              rows={3}
            />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="projStatus">Status</label>
              <select
                id="projStatus"
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
              >
                <option value="not-started">Not Started</option>
                <option value="in-progress">In Progress</option>
                <option value="on-hold">On Hold</option>
                <option value="completed">Completed</option>
              </select>
            </div>

            <div className="form-group">
              <label htmlFor="projPriority">Priority</label>
              <select
                id="projPriority"
                value={formData.priority}
                onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
              >
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="low">Low</option>
              </select>
            </div>
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="projProgress">Progress (%)</label>
              <input
                type="number"
                id="projProgress"
                min="0"
                max="100"
                value={formData.progress}
                onChange={(e) => setFormData({ ...formData, progress: parseInt(e.target.value) || 0 })}
              />
            </div>

            <div className="form-group">
              <label htmlFor="projDeadline">Deadline</label>
              <input
                type="date"
                id="projDeadline"
                value={formData.deadline}
                onChange={(e) => setFormData({ ...formData, deadline: e.target.value })}
              />
            </div>
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="projOwner">Owner</label>
              <input
                type="text"
                id="projOwner"
                value={formData.owner}
                onChange={(e) => setFormData({ ...formData, owner: e.target.value })}
                placeholder="Team member name..."
              />
            </div>

            <div className="form-group">
              <label htmlFor="projTags">Tags (comma-separated)</label>
              <input
                type="text"
                id="projTags"
                value={formData.tags}
                onChange={(e) => setFormData({ ...formData, tags: e.target.value })}
                placeholder="e.g. frontend, urgent"
              />
            </div>
          </div>

          <div className="modal-actions">
            <button type="button" className="btn btn-ghost" onClick={onClose}>
              Cancel
            </button>
            <button type="submit" className="btn btn-primary">
              {project ? 'Update Project' : 'Create Project'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
